In [10]:
#importing modules
import cv2
import numpy as np
import pandas as pd
import os
from skimage.feature import local_binary_pattern
from scipy.stats import itemfreq
from sklearn.preprocessing import normalize
import csv
import pickle
import joblib
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score
import sklearn.metrics as metrics

ImportError: cannot import name 'itemfreq' from 'scipy.stats' (/home/sumit/miniconda3/envs/scdt/lib/python3.8/site-packages/scipy/stats/__init__.py)

In [10]:
#lbp definiton for positve trainging images
def lbp_positive(folder_name,radius, no_points ):
    i=0
    label=1
    for filename in os.listdir(folder_name):
        #path
        path=os.path.join(folder_name,filename)
        
        #read the image
        a=cv2.imread(path)
        
        #change the image from rgb to grayscale
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        
        #apply gaussian filter
        img_gaussian = cv2.GaussianBlur(a,(3,3),0)
        
        #define the kernel for prewitt edge detection operat
        
        #change the image from rgb to grayscale
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        
        #apply gaussian filter
        img_gaussian = cv2.GaussianBlur(a,(3,3),0)
        
        #define the kernel for prewitt edge detection operator
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(img_gaussian, -1, kernelx)
        img_prewitty = cv2.filter2D(img_gaussian, -1, kernely)
        prewitt = img_prewittx + img_prewitty
        
        #apply canny edge detection.
        img_canny = cv2.Canny(a,100,200)
        final_img = prewitt + img_canny
        
        #set radius for LBP
        #radius = 3
        
        # Number of points to be considered as neighbourers 
        #no_points = 8 * radius
        
        # Uniform LBP is used
        lbp = local_binary_pattern(final_img, no_points, radius, method='uniform')
        
        # Calculate the histogram
        x = itemfreq(lbp.ravel())
        
        # Normalize the histogram
        hist = x[:, 1]/sum(x[:, 1])
        
        hist.reshape(26,-1)
        hist = np.append(hist, label)
        #writing features to csv files
        with open(r'finalcsv.csv', 'a',newline='') as f:
            writer = csv.writer(f)
            writer.writerow(hist)
        i=i+1
        if i==3000:
            break;

In [11]:
#lbp definition for negative training images
def lbp_negative(folder_name,radius, no_points ):
    i=0
    label=0
    for filename in os.listdir(folder_name):
        #path
        path=os.path.join(folder_name,filename)
        
        #read the image
        a=cv2.imread(path)
        
        #change the image from rgb to grayscale
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        
        #apply gaussian filter
        img_gaussian = cv2.GaussianBlur(a,(3,3),0)
        
        #define the kernel for prewitt edge detection operator
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(img_gaussian, -1, kernelx)
        img_prewitty = cv2.filter2D(img_gaussian, -1, kernely)
        prewitt = img_prewittx + img_prewitty
        
        #apply canny edge detection.
        img_canny = cv2.Canny(a,100,200)
        final_img = prewitt + img_canny
        
        #set radius for LBP
        #radius = 3
        
        # Number of points to be considered as neighbourers 
        #no_points = 8 * radius
        
        # Uniform LBP is used
        lbp = local_binary_pattern(final_img, no_points, radius, method='uniform')
        
        # Calculate the histogram
        x = itemfreq(lbp.ravel())
        
        # Normalize the histogram
        hist = x[:, 1]/sum(x[:, 1])
        
        hist.reshape(26,-1)
        hist = np.append(hist, label)
        #writing features to csv files
        with open(r'finalcsv.csv', 'a',newline='') as f:
            writer = csv.writer(f)
            writer.writerow(hist)
        i=i+1
        if i==3000:
            break;

In [12]:
#calling the lbp function for positive trainging images
lbp_positive(r"C:\Users\omkar\OneDrive\Desktop\College work\TY\ML FINAL PROJECT\Positiveforml",3,24)

D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\ipykernel_launcher.py:38: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`


In [13]:
#calling the lbp function for negative training images
lbp_negative(r"C:\Users\omkar\OneDrive\Desktop\College work\TY\ML FINAL PROJECT\Negativeforml",3,24)

D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\ipykernel_launcher.py:38: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`


In [14]:
#reading the csv file into 'data' variable
data= pd.read_csv('C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\finalcsv.csv',header=None)
data

0         1         2         3         4         5         6   \
0     0.079839  0.031633  0.036310  0.026257  0.016166  0.008209  0.005783   
1     0.069631  0.026936  0.036213  0.031574  0.020260  0.013876  0.009354   
2     0.076695  0.031225  0.034951  0.027227  0.015040  0.009917  0.007103   
3     0.070543  0.028062  0.035611  0.033030  0.020008  0.012478  0.008791   
4     0.068311  0.026335  0.034660  0.030973  0.021580  0.014089  0.009994   
...        ...       ...       ...       ...       ...       ...       ...   
5995  0.062392  0.019659  0.029110  0.035068  0.030468  0.021076  0.014438   
5996  0.069553  0.024142  0.034447  0.036213  0.026742  0.016476  0.010868   
5997  0.068330  0.022667  0.032661  0.036775  0.029362  0.018902  0.012362   
5998  0.066836  0.021464  0.032681  0.035009  0.028702  0.019911  0.013196   
5999  0.065730  0.022007  0.031070  0.033961  0.029090  0.019115  0.013119   

            7         8         9   ...        17        18        19  \
0     0.005123  0.004561  0.005162  ...  0.002989  0.002368  0.003086   
1     0.008325  0.008558  0.008403  ...  0.004852  0.004405  0.005861   
2     0.006327  0.005958  0.005803  ...  0.003377  0.002969  0.003881   
3     0.007666  0.006851  0.007180  ...  0.004211  0.004114  0.004522   
4     0.008364  0.007452  0.008694  ...  0.005570  0.004056  0.005473   
...        ...       ...       ...  ...       ...       ...       ...   
5995  0.013371  0.012847  0.015254  ...  0.009140  0.009102  0.010053   
5996  0.009296  0.009490  0.009587  ...  0.007336  0.007433  0.007258   
5997  0.011139  0.010965  0.011605  ...  0.007258  0.006035  0.008772   
5998  0.013585  0.012517  0.012789  ...  0.008714  0.007995  0.009257   
5999  0.013196  0.012614  0.011877  ...  0.009102  0.008869  0.008830   

            20        21        22        23        24        25   26  
0     0.004328  0.005997  0.005356  0.003784  0.312426  0.408896  1.0  
1     0.006637  0.008190  0.008015  0.005589  0.294300  0.372606  1.0  
2     0.004269  0.005085  0.004871  0.003260  0.321101  0.394555  1.0  
3     0.004813  0.006035  0.004871  0.003978  0.323468  0.369132  1.0  
4     0.006307  0.006482  0.006501  0.004890  0.306992  0.370277  1.0  
...        ...       ...       ...       ...       ...       ...  ...  
5995  0.008578  0.008597  0.008811  0.005861  0.253352  0.339479  0.0  
5996  0.007937  0.007374  0.005453  0.004095  0.293699  0.345378  0.0  
5997  0.006792  0.007472  0.005608  0.003454  0.292495  0.329465  0.0  
5998  0.008772  0.008539  0.006773  0.005589  0.265249  0.345863  0.0  
5999  0.008015  0.007530  0.006074  0.003940  0.289313  0.328223  0.0  

[6000 rows x 27 columns]

In [21]:
#splitting the data into x and y with 26 features for x and label column for y.
x = data.iloc[:,0:26].values
y = data.iloc[:,26].values

In [22]:
#scaling the data with the help of standardization
from sklearn.preprocessing import StandardScaler
std_obj = StandardScaler()
scalardata = std_obj.fit_transform(x)

In [23]:
#viewing the standardized data
scalardata

array([[ 2.36605999,  3.64625755,  1.82429339, ..., -0.713829  ,
         1.08919582,  2.41831966],
       [ 0.52304898,  1.73878691,  1.7811252 , ...,  0.5610166 ,
         0.37054206,  1.19746668],
       [ 1.79844063,  3.48073324,  1.21993876, ..., -1.08394547,
         1.43313397,  1.93585423],
       ...,
       [ 0.28829282,  0.0047227 ,  0.20116951, ..., -0.9468653 ,
         0.29898446, -0.25384678],
       [ 0.01849843, -0.48396813,  0.20980315, ...,  0.5610166 ,
        -0.78130449,  0.29782208],
       [-0.18121949, -0.26326904, -0.50678877, ..., -0.60416487,
         0.17279686, -0.29562998]])

In [24]:
#importing sklearn function for pca
from sklearn.decomposition import PCA

In [25]:
#applying PCA to reduce dimensions
pca = PCA(n_components=None)
pca.fit(scalardata)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [27]:
new_scalardata = pca.transform(scalardata)
new_scalardata

array([[ 1.30253200e+01, -1.14781184e+00,  3.14124897e+00, ...,
         2.34992369e-02, -7.94829918e-02, -1.38139287e-16],
       [ 6.26627658e+00,  7.57363931e-01,  1.31019157e+00, ...,
        -3.10514907e-01,  1.14777806e-01,  2.65901416e-17],
       [ 1.15583348e+01, -2.03078801e+00,  2.90010287e+00, ...,
         9.45394393e-02,  2.52975171e-02,  1.99078257e-15],
       ...,
       [ 2.22099084e-01, -1.35465740e+00, -1.74992052e+00, ...,
        -3.35926455e-01,  1.22109137e-01,  1.45004363e-16],
       [-1.38280353e+00,  1.35296677e+00, -1.64848723e+00, ...,
         1.28039540e-01,  1.22380783e-01,  1.13481539e-15],
       [-1.40868255e+00, -2.51507218e-01, -1.13344358e+00, ...,
         1.37654205e-01,  1.37549301e-01, -1.88290524e-15]])

In [28]:
new_scalardata.shape

(6000, 26)

In [29]:
new_scalardata = pd.DataFrame(new_scalardata)

In [30]:
new_scalardata

0         1         2         3         4         5         6   \
0     13.025320 -1.147812  3.141249 -1.407203 -0.618123  0.269438 -0.285013   
1      6.266277  0.757364  1.310192  0.204800  0.253008  1.487062 -0.765486   
2     11.558335 -2.030788  2.900103 -2.003131 -0.734042  0.340757  0.130253   
3      8.517733 -2.122113  0.406237 -0.566486  0.053056  1.042495  0.447386   
4      6.353095 -0.748050  1.083581 -0.864552  0.356737  0.956668 -0.078045   
...         ...       ...       ...       ...       ...       ...       ...   
5995  -4.298184  1.694826 -0.685913 -0.753854  1.156289 -0.119243  0.339126   
5996   2.448154 -0.412929 -1.481050  0.328945 -0.733546 -0.116789  0.706199   
5997   0.222099 -1.354657 -1.749921  0.102923  0.022114 -0.341273  0.246870   
5998  -1.382804  1.352967 -1.648487 -0.993851  0.127188  0.234405 -0.267140   
5999  -1.408683 -0.251507 -1.133444 -1.673723 -0.505760 -0.225619  0.297823   

            7         8         9   ...        16        17        18  \
0    -1.000018 -0.262830 -0.126182  ...  0.107763  0.055629  0.042797   
1    -0.255812 -0.112504  0.236247  ...  0.124229 -0.124303 -0.181518   
2    -0.802580 -0.616567 -0.089366  ...  0.050795 -0.283725  0.196271   
3    -0.084668 -0.423999  0.411282  ... -0.015877 -0.087901 -0.064072   
4    -0.071524  0.226781 -0.177651  ...  0.284428  0.048900  0.421424   
...        ...       ...       ...  ...       ...       ...       ...   
5995 -0.175940  0.014415  0.236920  ... -0.274034 -0.193388  0.127095   
5996  0.302345 -0.015092  0.088344  ... -0.020756 -0.167451  0.063203   
5997 -0.116025 -0.328617  0.411589  ...  0.209412  0.169790 -0.185954   
5998 -0.135703  0.000293 -0.145477  ...  0.332787  0.009730  0.240599   
5999  0.267031 -0.065843  0.216497  ... -0.171015  0.477406  0.007619   

            19        20        21        22        23        24            25  
0     0.015883 -0.268684 -0.126791 -0.084446  0.023499 -0.079483 -1.381393e-16  
1    -0.275319  0.167695 -0.106256  0.193449 -0.310515  0.114778  2.659014e-17  
2     0.088146  0.001811 -0.150540 -0.082788  0.094539  0.025298  1.990783e-15  
3    -0.086039 -0.127374  0.139301 -0.028043  0.017769 -0.099876  3.934728e-16  
4     0.195657 -0.114247  0.027879  0.243750 -0.065778  0.075370  2.489436e-15  
...        ...       ...       ...       ...       ...       ...           ...  
5995 -0.204722 -0.512110 -0.043807 -0.129971 -0.112594 -0.071441  6.169344e-16  
5996  0.047793  0.219792  0.260250 -0.049955  0.113507 -0.137939  4.992440e-16  
5997 -0.327820 -0.042437 -0.140284 -0.058423 -0.335926  0.122109  1.450044e-16  
5998 -0.488706 -0.090020 -0.000818 -0.193956  0.128040  0.122381  1.134815e-15  
5999 -0.393922  0.365637 -0.171328  0.062658  0.137654  0.137549 -1.882905e-15  

[6000 rows x 26 columns]

In [31]:
new_scalardata.shape

(6000, 26)

In [32]:
#Initially the explained variance sum of the full data with 26 features comes out to be 1.
print(pca.explained_variance_ratio_.sum())

1.0


In [61]:
#choosing only 18 columns from the data.
pca = PCA(n_components=18)
pca.fit(scalardata)

PCA(copy=True, iterated_power='auto', n_components=18, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [64]:
#save the pickle file of the pca model to the drive
filename = 'C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\PCA_Model.sav'
pickle.dump(pca, open(filename, 'wb'))

In [65]:
new_scalardata = pca.transform(scalardata)
new_scalardata

array([[ 1.30253200e+01, -1.14781184e+00,  3.14124897e+00, ...,
        -1.55866740e-01,  1.07762930e-01,  5.56291061e-02],
       [ 6.26627658e+00,  7.57363931e-01,  1.31019157e+00, ...,
        -2.76192695e-01,  1.24229211e-01, -1.24302894e-01],
       [ 1.15583348e+01, -2.03078801e+00,  2.90010287e+00, ...,
        -2.13978822e-01,  5.07951056e-02, -2.83725270e-01],
       ...,
       [ 2.22099084e-01, -1.35465740e+00, -1.74992052e+00, ...,
        -4.91427849e-02,  2.09412375e-01,  1.69790062e-01],
       [-1.38280353e+00,  1.35296677e+00, -1.64848723e+00, ...,
         4.77581114e-01,  3.32787004e-01,  9.72999184e-03],
       [-1.40868255e+00, -2.51507218e-01, -1.13344358e+00, ...,
         1.76174573e-01, -1.71014845e-01,  4.77405786e-01]])

In [66]:
new_scalardata.shape

(6000, 18)

In [67]:
#explained variance sum of the data with 18 columns comes out to be 99%.
print(pca.explained_variance_ratio_.sum()) 

0.990360708779925


In [69]:
#converting the data into dataframe
new_scalardata = pd.DataFrame(new_scalardata)
new_scalardata

0         1         2         3         4         5         6  \
0     13.025320 -1.147812  3.141249 -1.407203 -0.618123  0.269438 -0.285013   
1      6.266277  0.757364  1.310192  0.204800  0.253008  1.487062 -0.765486   
2     11.558335 -2.030788  2.900103 -2.003131 -0.734042  0.340757  0.130253   
3      8.517733 -2.122113  0.406237 -0.566486  0.053056  1.042495  0.447386   
4      6.353095 -0.748050  1.083581 -0.864552  0.356737  0.956668 -0.078045   
...         ...       ...       ...       ...       ...       ...       ...   
5995  -4.298184  1.694826 -0.685913 -0.753854  1.156289 -0.119243  0.339126   
5996   2.448154 -0.412929 -1.481050  0.328945 -0.733546 -0.116789  0.706199   
5997   0.222099 -1.354657 -1.749921  0.102923  0.022114 -0.341273  0.246870   
5998  -1.382804  1.352967 -1.648487 -0.993851  0.127188  0.234405 -0.267140   
5999  -1.408683 -0.251507 -1.133444 -1.673723 -0.505760 -0.225619  0.297823   

             7         8         9        10        11        12        13  \
0    -1.000018 -0.262830 -0.126182  0.451391  0.250481 -0.449014  0.012944   
1    -0.255812 -0.112504  0.236247 -0.035694 -0.094230  0.215514  0.197993   
2    -0.802580 -0.616567 -0.089366 -0.140864 -0.115965  0.074073  0.106007   
3    -0.084668 -0.423999  0.411282 -0.151000 -0.166272 -0.166718 -0.202987   
4    -0.071524  0.226781 -0.177651  0.035830  0.298667  0.026282  0.189246   
...        ...       ...       ...       ...       ...       ...       ...   
5995 -0.175940  0.014415  0.236920  0.421853 -0.320831  0.331370  0.326219   
5996  0.302345 -0.015092  0.088344  0.098513  0.324503 -0.244092 -0.442976   
5997 -0.116025 -0.328617  0.411589  0.636721 -0.531026 -0.058351  0.822338   
5998 -0.135703  0.000293 -0.145477 -0.054742 -0.352817 -0.083453  0.119906   
5999  0.267031 -0.065843  0.216497  0.252764 -0.122092  0.153038 -0.273876   

            14        15        16        17  
0    -0.288916 -0.155867  0.107763  0.055629  
1     0.107270 -0.276193  0.124229 -0.124303  
2     0.095371 -0.213979  0.050795 -0.283725  
3     0.350999  0.059044 -0.015877 -0.087901  
4     0.466544 -0.371295  0.284428  0.048900  
...        ...       ...       ...       ...  
5995 -0.410505 -0.408616 -0.274034 -0.193388  
5996  0.105378  0.107065 -0.020756 -0.167451  
5997  0.116245 -0.049143  0.209412  0.169790  
5998 -0.220282  0.477581  0.332787  0.009730  
5999 -0.439021  0.176175 -0.171015  0.477406  

[6000 rows x 18 columns]

In [71]:
#appending the label column to the dataframe.
label_column = pd.concat([new_scalardata, pd.DataFrame(y)],axis=1)
label_column

0         1         2         3         4         5         6   \
0     13.025320 -1.147812  3.141249 -1.407203 -0.618123  0.269438 -0.285013   
1      6.266277  0.757364  1.310192  0.204800  0.253008  1.487062 -0.765486   
2     11.558335 -2.030788  2.900103 -2.003131 -0.734042  0.340757  0.130253   
3      8.517733 -2.122113  0.406237 -0.566486  0.053056  1.042495  0.447386   
4      6.353095 -0.748050  1.083581 -0.864552  0.356737  0.956668 -0.078045   
...         ...       ...       ...       ...       ...       ...       ...   
5995  -4.298184  1.694826 -0.685913 -0.753854  1.156289 -0.119243  0.339126   
5996   2.448154 -0.412929 -1.481050  0.328945 -0.733546 -0.116789  0.706199   
5997   0.222099 -1.354657 -1.749921  0.102923  0.022114 -0.341273  0.246870   
5998  -1.382804  1.352967 -1.648487 -0.993851  0.127188  0.234405 -0.267140   
5999  -1.408683 -0.251507 -1.133444 -1.673723 -0.505760 -0.225619  0.297823   

            7         8         9         10        11        12        13  \
0    -1.000018 -0.262830 -0.126182  0.451391  0.250481 -0.449014  0.012944   
1    -0.255812 -0.112504  0.236247 -0.035694 -0.094230  0.215514  0.197993   
2    -0.802580 -0.616567 -0.089366 -0.140864 -0.115965  0.074073  0.106007   
3    -0.084668 -0.423999  0.411282 -0.151000 -0.166272 -0.166718 -0.202987   
4    -0.071524  0.226781 -0.177651  0.035830  0.298667  0.026282  0.189246   
...        ...       ...       ...       ...       ...       ...       ...   
5995 -0.175940  0.014415  0.236920  0.421853 -0.320831  0.331370  0.326219   
5996  0.302345 -0.015092  0.088344  0.098513  0.324503 -0.244092 -0.442976   
5997 -0.116025 -0.328617  0.411589  0.636721 -0.531026 -0.058351  0.822338   
5998 -0.135703  0.000293 -0.145477 -0.054742 -0.352817 -0.083453  0.119906   
5999  0.267031 -0.065843  0.216497  0.252764 -0.122092  0.153038 -0.273876   

            14        15        16        17   0   
0    -0.288916 -0.155867  0.107763  0.055629  1.0  
1     0.107270 -0.276193  0.124229 -0.124303  1.0  
2     0.095371 -0.213979  0.050795 -0.283725  1.0  
3     0.350999  0.059044 -0.015877 -0.087901  1.0  
4     0.466544 -0.371295  0.284428  0.048900  1.0  
...        ...       ...       ...       ...  ...  
5995 -0.410505 -0.408616 -0.274034 -0.193388  0.0  
5996  0.105378  0.107065 -0.020756 -0.167451  0.0  
5997  0.116245 -0.049143  0.209412  0.169790  0.0  
5998 -0.220282  0.477581  0.332787  0.009730  0.0  
5999 -0.439021  0.176175 -0.171015  0.477406  0.0  

[6000 rows x 19 columns]

In [72]:
#saving the dataframe as as csv file.
csv_data=label_column.to_csv('C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\FinalPCAFV.csv', mode='a',header=False,index=False)

# Training , Testing and classification

In [26]:
#reading the final training data.
train_data = pd.read_csv('C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\FinalPCAFV.csv',header=None)

In [27]:
train_data

0         1         2         3         4         5         6   \
0     13.025320 -1.147812  3.141249 -1.407203 -0.618123  0.269438 -0.285013   
1      6.266277  0.757364  1.310192  0.204800  0.253008  1.487062 -0.765486   
2     11.558335 -2.030788  2.900103 -2.003131 -0.734042  0.340757  0.130253   
3      8.517733 -2.122113  0.406237 -0.566486  0.053056  1.042495  0.447386   
4      6.353095 -0.748050  1.083581 -0.864552  0.356737  0.956668 -0.078045   
...         ...       ...       ...       ...       ...       ...       ...   
5995  -4.298184  1.694826 -0.685913 -0.753854  1.156289 -0.119243  0.339126   
5996   2.448154 -0.412929 -1.481050  0.328945 -0.733546 -0.116789  0.706199   
5997   0.222099 -1.354657 -1.749921  0.102923  0.022114 -0.341273  0.246870   
5998  -1.382804  1.352967 -1.648487 -0.993851  0.127188  0.234405 -0.267140   
5999  -1.408683 -0.251507 -1.133444 -1.673723 -0.505760 -0.225619  0.297823   

            7         8         9         10        11        12        13  \
0    -1.000018 -0.262830 -0.126182  0.451391  0.250481 -0.449014  0.012944   
1    -0.255812 -0.112504  0.236247 -0.035694 -0.094230  0.215514  0.197993   
2    -0.802580 -0.616567 -0.089366 -0.140864 -0.115965  0.074073  0.106007   
3    -0.084668 -0.423999  0.411282 -0.151000 -0.166272 -0.166718 -0.202987   
4    -0.071524  0.226781 -0.177651  0.035830  0.298667  0.026282  0.189246   
...        ...       ...       ...       ...       ...       ...       ...   
5995 -0.175940  0.014415  0.236920  0.421853 -0.320831  0.331370  0.326219   
5996  0.302345 -0.015092  0.088344  0.098513  0.324503 -0.244092 -0.442976   
5997 -0.116025 -0.328617  0.411589  0.636721 -0.531026 -0.058351  0.822338   
5998 -0.135703  0.000293 -0.145477 -0.054742 -0.352817 -0.083453  0.119906   
5999  0.267031 -0.065843  0.216497  0.252764 -0.122092  0.153038 -0.273876   

            14        15        16        17   18  
0    -0.288916 -0.155867  0.107763  0.055629  1.0  
1     0.107270 -0.276193  0.124229 -0.124303  1.0  
2     0.095371 -0.213979  0.050795 -0.283725  1.0  
3     0.350999  0.059044 -0.015877 -0.087901  1.0  
4     0.466544 -0.371295  0.284428  0.048900  1.0  
...        ...       ...       ...       ...  ...  
5995 -0.410505 -0.408616 -0.274034 -0.193388  0.0  
5996  0.105378  0.107065 -0.020756 -0.167451  0.0  
5997  0.116245 -0.049143  0.209412  0.169790  0.0  
5998 -0.220282  0.477581  0.332787  0.009730  0.0  
5999 -0.439021  0.176175 -0.171015  0.477406  0.0  

[6000 rows x 19 columns]

In [28]:
#assigning x the columns from 1 to 18 for training
x = train_data.iloc[:,0:18].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = train_data.iloc[:,18]
print("Y values")
print(y)

X values
[[ 1.30253200e+01 -1.14781184e+00  3.14124897e+00 ... -1.55866740e-01
   1.07762930e-01  5.56291061e-02]
 [ 6.26627658e+00  7.57363931e-01  1.31019157e+00 ... -2.76192695e-01
   1.24229211e-01 -1.24302894e-01]
 [ 1.15583348e+01 -2.03078801e+00  2.90010287e+00 ... -2.13978822e-01
   5.07951056e-02 -2.83725270e-01]
 ...
 [ 2.22099084e-01 -1.35465740e+00 -1.74992052e+00 ... -4.91427849e-02
   2.09412375e-01  1.69790062e-01]
 [-1.38280353e+00  1.35296677e+00 -1.64848723e+00 ...  4.77581114e-01
   3.32787004e-01  9.72999184e-03]
 [-1.40868255e+00 -2.51507218e-01 -1.13344358e+00 ...  1.76174573e-01
  -1.71014845e-01  4.77405786e-01]]
Y values
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
5995    0.0
5996    0.0
5997    0.0
5998    0.0
5999    0.0
Name: 18, Length: 6000, dtype: float64


In [29]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

# Decision Tree

In [30]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model_dt = DecisionTreeClassifier(max_depth=13)
#training the model with the Training Variables 
model_dt.fit(x_train, y_train)
#dumping the decision tree classifier model to the disk
joblib.dump(model_dt,"model_dt")
#predicting the target variable using testing variables
y_pred1 = model_dt.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")
print("Train Accuracy:",model_dt.score(x_train, y_train))
print("Test Accuracy:",model_dt.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred1, pos_label='positive', average='micro')) # true positive rate, Sensitivity
print("F2 Score: ",metrics.fbeta_score(y_test, y_pred1, pos_label='positive', average='micro', beta=2.0))
print("F1 Score: ",metrics.f1_score(y_test, y_pred1, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred1))

Decision Tree Results
Decision Tree Accuracy:  85.83333333333333 %
Train Accuracy: 0.993125
Test Accuracy: 0.8583333333333333
Precision Score:  0.8583333333333333
Recall Score:  0.8583333333333333
F2 Score:  0.8583333333333333
F1 Score:  0.8583333333333333
Confusion Matrix: 
[[534  82]
 [ 88 496]]


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# Random Forest

In [31]:
#Random Forest classifier
model_rf = RandomForestClassifier(n_estimators = 50)
#training the model with train variables
model_rf.fit(x_train, y_train)
#dumping the random forest classifier model to the disk
joblib.dump(model_rf,"model_rf")
#predicting with the trained random forest model
y_pred2 = model_rf.predict(x_test)
print("Random Forest Clasifier")
print("Train Accuracy:",model_rf.score(x_train, y_train))
print("Test Accuracy:",model_rf.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred2, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred2,))

Random Forest Clasifier
Train Accuracy: 0.9997916666666666
Test Accuracy: 0.9016666666666666
Precision Score:  0.9016666666666666
Recall Score:  0.9016666666666666
F1 Score:  0.9016666666666667
Confusion Matrix: 
[[555  61]
 [ 57 527]]


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# KNN

In [32]:
#KNN classifier
model_knn = KNeighborsClassifier(n_neighbors = 5)
model_knn.fit(x_train, y_train)
#dumping the KNN classifier model to the disk.
joblib.dump(model_knn,"model_knn")
y_pred3 = model_knn.predict(x_test)
print("KNN")
print("Train Accuracy:",model_knn.score(x_train, y_train))
print("Test Accuracy:",model_knn.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred3, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred3,))

KNN
Train Accuracy: 0.9435416666666666
Test Accuracy: 0.9141666666666667
Precision Score:  0.9141666666666667
Recall Score:  0.9141666666666667
F1 Score:  0.9141666666666667
Confusion Matrix: 
[[562  54]
 [ 49 535]]


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# SVM

In [102]:
#svm classifier
model_svm = svm.SVC(kernel='linear') # Linear Kernel
model_svm.fit(x_train, y_train)
#dumping the svm classifier model to the disk
joblib.dump(model_svm,"model_svm")
#prediction
y_pred4 = model_svm.predict(x_test)
print("SVM Linear kernel")
print("Train Accuracy:",model_svm.score(x_train, y_train))
print("Test Accuracy:",model_svm.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred4, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred4,))

SVM Linear kernel
Train Accuracy: 0.893125
Test Accuracy: 0.8975
Precision Score:  0.8975
Recall Score:  0.8975
F1 Score:  0.8975
Confusion Matrix: 
[[550  66]
 [ 57 527]]


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# Gaussian Naive Bayes

In [97]:
#gaussian naive bayes classifier
model_nb = GaussianNB().fit(x_train, y_train)
#dumping the naive bayes classifier model to the disk
joblib.dump(model_nb,"model_nb")
y_pred8 = model_nb.predict(x_test)
print("Gaussian NB")
print("Train Accuracy:",model_nb.score(x_train, y_train))
print("Test Accuracy:",model_nb.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred8, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred8,))

Gaussian NB
Train Accuracy: 0.88625
Test Accuracy: 0.9041666666666667
Precision Score:  0.9041666666666667
Recall Score:  0.9041666666666667
F1 Score:  0.9041666666666667
Confusion Matrix: 
[[570  46]
 [ 69 515]]


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# Xgboost 

In [105]:
#xgboost classifier
model_xgboost = XGBClassifier().fit(x_train, y_train)
#dumping the xgboost classifier model to the disk.
joblib.dump(model_nb,"model_xgboost")
#prediction
y_pred5 = model_xgboost.predict(x_test)
print("XGboost")
print("Train Accuracy:",model_xgboost.score(x_train, y_train))
print("Test Accuracy:",model_xgboost.score(x_test, y_test))
print("Precision Score: ",metrics.precision_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y_test, y_pred5, pos_label='positive', average='micro'))
print("Confusion Matrix: ")
print(confusion_matrix(y_test, y_pred5,))

XGboost
Train Accuracy: 1.0
Test Accuracy: 0.9341666666666667
Precision Score:  0.9341666666666667
Recall Score:  0.9341666666666667
F1 Score:  0.9341666666666667
Confusion Matrix: 
[[575  41]
 [ 38 546]]


# Testing with exclusive 1600 images

In [5]:
#lbp definiton for positve testing images
def lbp_positive_testing(folder_name,radius, no_points ):
    i=0
    label=1
    for filename in os.listdir(folder_name):
        #path
        path=os.path.join(folder_name,filename)
        
        #read the image
        a=cv2.imread(path)
        
        #change the image from rgb to grayscale
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        
        #apply gaussian filter
        img_gaussian = cv2.GaussianBlur(a,(3,3),0)
        
        #define the kernel for prewitt edge detection operator
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(img_gaussian, -1, kernelx)
        img_prewitty = cv2.filter2D(img_gaussian, -1, kernely)
        prewitt = img_prewittx + img_prewitty
        
        #apply canny edge detection.
        img_canny = cv2.Canny(a,100,200)
        final_img = prewitt + img_canny
        
        #set radius for LBP
        #radius = 3
        
        # Number of points to be considered as neighbourers 
        #no_points = 8 * radius
        
        # Uniform LBP is used
        lbp = local_binary_pattern(final_img, no_points, radius, method='uniform')
        
        # Calculate the histogram
        x = itemfreq(lbp.ravel())
        
        # Normalize the histogram
        hist = x[:, 1]/sum(x[:, 1])
        
        hist.reshape(26,-1)
        hist = np.append(hist, label)
        #writing features to csv files
        with open(r'testingcsv.csv', 'a',newline='') as f:
            writer = csv.writer(f)
            writer.writerow(hist)
        i=i+1
        if i==3000:
            break;

In [6]:
#lbp definition for negative testing images
def lbp_negative_testing(folder_name,radius, no_points ):
    i=0
    label=0
    for filename in os.listdir(folder_name):
        #path
        path=os.path.join(folder_name,filename)
        
        #read the image
        a=cv2.imread(path)
        
        #change the image from rgb to grayscale
        a = cv2.cvtColor(a, cv2.COLOR_BGR2GRAY)
        
        #apply gaussian filter
        img_gaussian = cv2.GaussianBlur(a,(3,3),0)
        
        #define the kernel for prewitt edge detection operator
        kernelx = np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
        kernely = np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
        img_prewittx = cv2.filter2D(img_gaussian, -1, kernelx)
        img_prewitty = cv2.filter2D(img_gaussian, -1, kernely)
        prewitt = img_prewittx + img_prewitty
        
        #apply canny edge detection.
        img_canny = cv2.Canny(a,100,200)
        final_img = prewitt + img_canny
        
        #set radius for LBP
        #radius = 3
        
        # Number of points to be considered as neighbourers 
        #no_points = 8 * radius
        
        # Uniform LBP is used
        lbp = local_binary_pattern(final_img, no_points, radius, method='uniform')
        
        # Calculate the histogram
        x = itemfreq(lbp.ravel())
        
        # Normalize the histogram
        hist = x[:, 1]/sum(x[:, 1])
        
        hist.reshape(26,-1)
        hist = np.append(hist, label)
        #writing features to csv files
        with open(r'testingcsv.csv', 'a',newline='') as f:
            writer = csv.writer(f)
            writer.writerow(hist)
        i=i+1
        if i==3000:
            break;

In [7]:
#calling the lbp function for positive testing images
lbp_positive_testing(r"C:\Users\omkar\OneDrive\Desktop\College work\TY\ML FINAL PROJECT\testing_positive",3,24)

D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\ipykernel_launcher.py:39: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`


In [8]:
#calling the lbp function for negative testing images
lbp_negative_testing(r"C:\Users\omkar\OneDrive\Desktop\College work\TY\ML FINAL PROJECT\testing_negative",3,24)

D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\ipykernel_launcher.py:39: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`


In [9]:
#reading the csv file.
data= pd.read_csv('C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\testingcsv.csv',header=None)
data

0         1         2         3         4         5         6   \
0     0.061693  0.022939  0.032292  0.034117  0.027053  0.018184  0.013313   
1     0.066817  0.024084  0.033379  0.033360  0.025345  0.017815  0.012226   
2     0.068330  0.024161  0.030507  0.032001  0.026373  0.018417  0.012343   
3     0.069728  0.025403  0.032215  0.034932  0.025811  0.015254  0.011663   
4     0.067632  0.024355  0.031613  0.032098  0.024491  0.017291  0.012168   
...        ...       ...       ...       ...       ...       ...       ...   
1595  0.064663  0.021658  0.031322  0.034738  0.029614  0.020881  0.014380   
1596  0.082303  0.028683  0.035902  0.033864  0.020726  0.012634  0.007918   
1597  0.056182  0.019368  0.030061  0.033088  0.026703  0.020649  0.015292   
1598  0.061538  0.020532  0.030895  0.037125  0.029168  0.020319  0.015448   
1599  0.069514  0.022958  0.033748  0.035999  0.027130  0.018009  0.012207   

            7         8         9   ...        17        18        19  \
0     0.011954  0.013119  0.013429  ...  0.007239  0.007083  0.008325   
1     0.010615  0.010460  0.009781  ...  0.006462  0.005550  0.007200   
2     0.009994  0.010053  0.010577  ...  0.005997  0.006307  0.007646   
3     0.010091  0.009315  0.009839  ...  0.006152  0.006152  0.006909   
4     0.010596  0.010538  0.010674  ...  0.007258  0.006889  0.008422   
...        ...       ...       ...  ...       ...       ...       ...   
1595  0.014516  0.012634  0.013546  ...  0.008151  0.007510  0.007433   
1596  0.006870  0.006249  0.006482  ...  0.004502  0.003998  0.004561   
1597  0.014438  0.015370  0.017757  ...  0.011372  0.009742  0.011081   
1598  0.012459  0.012071  0.013410  ...  0.008869  0.008578  0.008655   
1599  0.011333  0.010693  0.010751  ...  0.007258  0.006734  0.008054   

            20        21        22        23        24        25   26  
0     0.009238  0.008617  0.007161  0.004522  0.272914  0.331988  1.0  
1     0.007491  0.007161  0.007607  0.005764  0.266277  0.374624  1.0  
2     0.006540  0.005706  0.005162  0.003745  0.304741  0.344602  1.0  
3     0.007510  0.006831  0.005531  0.004075  0.301966  0.345786  1.0  
4     0.007258  0.007530  0.006307  0.005337  0.286266  0.357604  1.0  
...        ...       ...       ...       ...       ...       ...  ...  
1595  0.007898  0.006715  0.006870  0.005123  0.277223  0.333812  0.0  
1596  0.007122  0.007588  0.007258  0.005608  0.293621  0.387296  0.0  
1597  0.010557  0.009626  0.007646  0.005453  0.270547  0.294494  0.0  
1598  0.008131  0.008617  0.005453  0.003959  0.288226  0.306041  0.0  
1599  0.007860  0.007801  0.007491  0.005007  0.266549  0.367191  0.0  

[1600 rows x 27 columns]

In [10]:
#splitting the data into 
x = data.iloc[:,0:26].values
y = data.iloc[:,26].values

In [11]:
#scaling the testing data with standardization
from sklearn.preprocessing import StandardScaler
std_obj = StandardScaler()
scalardata = std_obj.fit_transform(x)

In [12]:
scalardata

array([[-0.87281928,  0.32836133,  0.2551524 , ..., -0.01354229,
        -0.68606689,  0.1097835 ],
       [ 0.09991481,  0.83780845,  0.7226518 , ...,  1.11663763,
        -0.97310442,  1.58480353],
       [ 0.38731351,  0.87234724, -0.51288232, ..., -0.71990475,
         0.69037036,  0.54617996],
       ...,
       [-1.91924534, -1.2604229 , -0.704891  , ...,  0.83409265,
        -0.78846039, -1.18732105],
       [-0.90229607, -0.74234108, -0.34591825, ..., -0.52565507,
        -0.02386629, -0.78785045],
       [ 0.61207404,  0.33699603,  0.88126767, ...,  0.42793424,
        -0.96135434,  1.32766531]])

In [13]:
#loading the already trained PCA model.
pca = pickle.load(open('C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\PCA_Model.sav','rb'))

In [15]:
#transforming the testing data with 18 columns
new_scalardata = pca.transform(scalardata)

In [16]:
new_scalardata

array([[-1.3608204 ,  0.76463133,  0.39013855, ..., -0.16289829,
        -0.19090485, -0.19270764],
       [ 3.00892559,  1.43514039,  0.01685336, ..., -0.31711906,
         0.07148968, -0.13345234],
       [ 3.08309845, -1.7423547 ,  0.08320101, ..., -0.35545487,
        -0.08623512, -0.34017242],
       ...,
       [-7.24790402,  1.94917079,  1.15591419, ..., -0.03276779,
         0.575312  , -0.20130642],
       [-3.27921173, -0.784945  , -1.21794194, ..., -0.05829294,
        -0.13852957,  0.04687211],
       [ 2.34452407,  1.65501368, -1.7123903 , ..., -0.23235169,
        -0.04403905,  0.02220744]])

In [17]:
new_scalardata = pd.DataFrame(new_scalardata)

In [18]:
#appending the label to the final testing data.
testing_label_column = pd.concat([new_scalardata, pd.DataFrame(y)],axis=1)
testing_label_column

0         1         2         3         4         5         6   \
0     -1.360820  0.764631  0.390139  0.533078 -0.063846  0.815354 -0.755753   
1      3.008926  1.435140  0.016853 -0.502297  1.227377  0.919127  0.124087   
2      3.083098 -1.742355  0.083201 -1.777882  0.346577 -0.492225  0.344807   
3      3.879804 -0.760606 -0.459081 -0.216910  0.027360 -0.202904  0.403361   
4      2.679669  0.932757  0.348940 -1.550542  0.179425  0.301049  0.272849   
...         ...       ...       ...       ...       ...       ...       ...   
1595  -1.181812 -0.050284 -1.282469 -1.355179  1.384810  0.659021 -0.242646   
1596  10.161428  1.670578  0.297510  0.722486  0.411563 -0.302222 -0.064135   
1597  -7.247904  1.949171  1.155914 -0.294698 -1.104170  1.000562 -0.397174   
1598  -3.279212 -0.784945 -1.217942  0.350647 -0.245601  0.094625  0.091969   
1599   2.344524  1.655014 -1.712390 -0.164453  0.756898  0.344428  0.011542   

            7         8         9         10        11        12        13  \
0    -0.074695 -0.789802 -0.476626 -0.357939  0.219017 -0.185414  0.586632   
1    -0.888523 -0.219487 -0.629717  0.080140  0.146871  0.171150  0.473365   
2     0.027006 -0.276726 -0.804279  0.572477 -0.483337  0.269811  0.028595   
3     0.367467 -0.802595 -0.260181 -0.205700  0.046845  0.050155 -0.090197   
4     0.127642 -0.239756 -0.130384  0.159657 -0.696802  0.014130  0.057531   
...        ...       ...       ...       ...       ...       ...       ...   
1595 -0.785397 -0.346143 -0.600351 -0.007443  0.277206  0.637114 -0.222885   
1596 -0.382794 -0.505086  0.437901 -0.369121  0.767236  0.432063 -0.282709   
1597  0.423494  0.133818  0.314010 -0.809216 -0.155703  0.078893  0.409458   
1598  0.146347 -0.489171  0.646635  0.038247 -0.201336 -0.718752 -0.377942   
1599 -0.536939 -0.252446 -0.129789  0.008512 -0.259502  0.252704  0.213077   

            14        15        16        17   0   
0    -0.227226 -0.162898 -0.190905 -0.192708  1.0  
1     0.563691 -0.317119  0.071490 -0.133452  1.0  
2     0.241710 -0.355455 -0.086235 -0.340172  1.0  
3     0.106812  0.228399 -0.084281  0.283524  1.0  
4     0.260236  0.005547  0.303736 -0.190984  1.0  
...        ...       ...       ...       ...  ...  
1595 -0.065938  0.392196  0.047670  0.320624  0.0  
1596  0.325316  0.329139  0.530789 -0.136678  0.0  
1597 -0.147360 -0.032768  0.575312 -0.201306  0.0  
1598  0.769535 -0.058293 -0.138530  0.046872  0.0  
1599 -0.032706 -0.232352 -0.044039  0.022207  0.0  

[1600 rows x 19 columns]

In [20]:
#saving the datafile into csv format.
csv_data_t1=testing_label_column.to_csv('C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\testing_FinalPCAFV.csv', mode='a',header=False,index=False)

In [33]:
#reading the csv file.
data2= pd.read_csv(r'C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\testing_FinalPCAFV.csv',header=None)
data2

0         1         2         3         4         5         6   \
0     -1.360820  0.764631  0.390139  0.533078 -0.063846  0.815354 -0.755753   
1      3.008926  1.435140  0.016853 -0.502297  1.227377  0.919127  0.124087   
2      3.083098 -1.742355  0.083201 -1.777882  0.346577 -0.492225  0.344807   
3      3.879804 -0.760606 -0.459081 -0.216910  0.027360 -0.202904  0.403361   
4      2.679669  0.932757  0.348940 -1.550542  0.179425  0.301049  0.272849   
...         ...       ...       ...       ...       ...       ...       ...   
1595  -1.181812 -0.050284 -1.282469 -1.355179  1.384810  0.659021 -0.242646   
1596  10.161428  1.670578  0.297510  0.722486  0.411563 -0.302222 -0.064135   
1597  -7.247904  1.949171  1.155914 -0.294698 -1.104170  1.000562 -0.397174   
1598  -3.279212 -0.784945 -1.217942  0.350647 -0.245601  0.094625  0.091969   
1599   2.344524  1.655014 -1.712390 -0.164453  0.756898  0.344428  0.011542   

            7         8         9         10        11        12        13  \
0    -0.074695 -0.789802 -0.476626 -0.357939  0.219017 -0.185414  0.586632   
1    -0.888523 -0.219487 -0.629717  0.080140  0.146871  0.171150  0.473365   
2     0.027006 -0.276726 -0.804279  0.572477 -0.483337  0.269811  0.028595   
3     0.367467 -0.802595 -0.260181 -0.205700  0.046845  0.050155 -0.090197   
4     0.127642 -0.239756 -0.130384  0.159657 -0.696802  0.014130  0.057531   
...        ...       ...       ...       ...       ...       ...       ...   
1595 -0.785397 -0.346143 -0.600351 -0.007443  0.277206  0.637114 -0.222885   
1596 -0.382794 -0.505086  0.437901 -0.369121  0.767236  0.432063 -0.282709   
1597  0.423494  0.133818  0.314010 -0.809216 -0.155703  0.078893  0.409458   
1598  0.146347 -0.489171  0.646635  0.038247 -0.201336 -0.718752 -0.377942   
1599 -0.536939 -0.252446 -0.129789  0.008512 -0.259502  0.252704  0.213077   

            14        15        16        17   18  
0    -0.227226 -0.162898 -0.190905 -0.192708  1.0  
1     0.563691 -0.317119  0.071490 -0.133452  1.0  
2     0.241710 -0.355455 -0.086235 -0.340172  1.0  
3     0.106812  0.228399 -0.084281  0.283524  1.0  
4     0.260236  0.005547  0.303736 -0.190984  1.0  
...        ...       ...       ...       ...  ...  
1595 -0.065938  0.392196  0.047670  0.320624  0.0  
1596  0.325316  0.329139  0.530789 -0.136678  0.0  
1597 -0.147360 -0.032768  0.575312 -0.201306  0.0  
1598  0.769535 -0.058293 -0.138530  0.046872  0.0  
1599 -0.032706 -0.232352 -0.044039  0.022207  0.0  

[1600 rows x 19 columns]

In [34]:
#assigning x the columns from 1 to 18 for training
x1 = data2.iloc[:,0:18].values
print("X values")
print(x1)

#assigning y with the column "Class" as target variable
y1 = data2.iloc[:,18]
print("Y values")
print(y1)

X values
[[-1.3608204   0.76463133  0.39013855 ... -0.16289829 -0.19090485
  -0.19270764]
 [ 3.00892559  1.43514039  0.01685336 ... -0.31711906  0.07148968
  -0.13345234]
 [ 3.08309845 -1.7423547   0.08320101 ... -0.35545487 -0.08623512
  -0.34017242]
 ...
 [-7.24790402  1.94917079  1.15591419 ... -0.03276779  0.575312
  -0.20130642]
 [-3.27921173 -0.784945   -1.21794194 ... -0.05829294 -0.13852957
   0.04687211]
 [ 2.34452407  1.65501368 -1.7123903  ... -0.23235169 -0.04403905
   0.02220744]]
Y values
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
1595    0.0
1596    0.0
1597    0.0
1598    0.0
1599    0.0
Name: 18, Length: 1600, dtype: float64


# Decision Tree

In [35]:
#loading the decision tree classifier.
model_dt = joblib.load("C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\model_dt")
#prediction
y_dt = model_dt.predict(x1)
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y1, y_dt)*100,"%")

Decision Tree Results
Decision Tree Accuracy:  83.5625 %


# Random Forest

In [36]:
#loading the Random forest classifier.
model_rf = joblib.load("C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\model_rf")
#prediction
y_rf = model_rf.predict(x1)
print("Random Forest Clasifier")
print("Random Forest Clasifier: ",accuracy_score(y1, y_rf)*100,"%")
print("Precision Score: ",metrics.precision_score(y1, y_rf, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y1, y_rf, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y1, y_rf, pos_label='positive', average='micro'))

Random Forest Clasifier
Random Forest Clasifier:  89.5625 %
Precision Score:  0.895625
Recall Score:  0.895625
F1 Score:  0.895625


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# KNN

In [37]:
#loading the KNN classifier.
model_knn = joblib.load("C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\model_knn")
#prediction
y_knn = model_knn.predict(x1)
print("KNN")
print("KNN: ",accuracy_score(y1, y_knn)*100,"%")
print("Precision Score: ",metrics.precision_score(y1, y_knn, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y1, y_knn, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y1, y_knn, pos_label='positive', average='micro'))

KNN
KNN:  88.6875 %
Precision Score:  0.886875
Recall Score:  0.886875
F1 Score:  0.886875


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# SVM

In [38]:
#loading the svm classifier.
model_svm = joblib.load("C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\model_svm")
#prediction
y_svm = model_svm.predict(x1)
print("SVM")
print("SVM: ",accuracy_score(y1, y_svm)*100,"%")
print("Precision Score: ",metrics.precision_score(y1, y_svm, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y1, y_svm, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y1, y_svm, pos_label='positive', average='micro'))

SVM
SVM:  88.8125 %
Precision Score:  0.888125
Recall Score:  0.888125
F1 Score:  0.8881250000000002


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# Gaussian Naive Bayes

In [39]:
#loading the gaussian naive bayes classifier.
model_nb = joblib.load("C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\model_nb")
#prediction
y_nb = model_nb.predict(x1)
print("Guassian NB")
print("Guassian NB: ",accuracy_score(y1, y_nb)*100,"%")
print("Precision Score: ",metrics.precision_score(y1, y_nb, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y1, y_nb, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y1, y_nb, pos_label='positive', average='micro'))

Guassian NB
Guassian NB:  88.625 %
Precision Score:  0.88625
Recall Score:  0.88625
F1 Score:  0.88625


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


# Xgboost

In [41]:
#loading the xgboost tree classifier.
model_xgboost = joblib.load("C:\\Users\\omkar\\OneDrive\\Desktop\\College work\\TY\\ML FINAL PROJECT\\model_xgboost")
#prediction
y_xgboost = model_xgboost.predict(x1)
print("XGboost")
print("XGboost: ",accuracy_score(y1, y_nb)*100,"%")
print("Precision Score: ",metrics.precision_score(y1, y_xgboost, pos_label='positive', average='micro'))
print("Recall Score: ",metrics.recall_score(y1, y_xgboost, pos_label='positive', average='micro'))
print("F1 Score: ",metrics.f1_score(y1, y_xgboost, pos_label='positive', average='micro'))

XGboost
XGboost:  88.625 %
Precision Score:  0.88625
Recall Score:  0.88625
F1 Score:  0.88625


D:\DedicatedSoftwares\Anaconda3forme\lib\site-packages\sklearn\metrics\classification.py:1259: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
