In [ ]:
#Required libraries
import numpy as np
import pandas as pd                               
import os
import csv
import cv2
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [ ]:
#Path of dataset
folder1="Dataset/Broken Chair"
folder2="Dataset/Normal Chair"

## Feature Extraction

### Applying FAST + BRIEF Feature Descriptor on the dataset

In [ ]:
#Applying FAST + BRIEF Feature descriptor on folder1
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
  
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder1.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (133, 32)
descriptor shape  1  :  (60, 32)
descriptor shape  2  :  (74, 32)
descriptor shape  3  :  (66, 32)
descriptor shape  4  :  (67, 32)
descriptor shape  5  :  (99, 32)
descriptor shape  6  :  (139, 32)
descriptor shape  7  :  (131, 32)
descriptor shape  8  :  (184, 32)
descriptor shape  9  :  (51, 32)
descriptor shape  10  :  (164, 32)
descriptor shape  11  :  (137, 32)
descriptor shape  12  :  (76, 32)
descriptor shape  13  :  (41, 32)
descriptor shape  14  :  (114, 32)
descriptor shape  15  :  (97, 32)
descriptor shape  16  :  (102, 32)
descriptor shape  17  :  (93, 32)
descriptor shape  18  :  (104, 32)
descriptor shape  19  :  (94, 32)
descriptor shape  20  :  (103, 32)
descriptor shape  21  :  (37, 32)
descriptor shape  22  :  (45, 32)
descriptor shape  23  :  (65, 32)
descriptor shape  24  :  (14, 32)
descriptor shape  25  :  (88, 32)
descriptor shape  26  :  (67, 32)
descriptor shape  27  :  (48, 32)
descriptor shape  28  :  (42, 32)
descriptor sha

In [ ]:
#reading previously saved feature descriptor csv file of folder1 and save it into a dataframe
data1 = pd.read_csv('folder1.csv',header=None,dtype='uint8')

data1=data1.astype(np.uint8) 
data1

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0      177   55   46    0   47  114  197   28   54  251  ...  201  168  217   
1      177   55   60   72   47  114  197  156   22  251  ...  221  168  185   
2      177   55   30    2   45   82  197   28  116  251  ...  217  168  169   
3      177  183   22   34   47  114  229   12   54  243  ...  201  168  201   
4      177   55   62   96   43   66  197  156   54  251  ...  205  168  185   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
75071   27    5  232  197  172  131  129  217  230   17  ...  239    8  243   
75072  176   21  106  197  104  233  169  152  246  122  ...  223  160  243   
75073   27    7  176  116   35  147   53   92    3   19  ...  255   34  249   
75074  181  185   56  192   32  201  137  187  246   90  ...  187  193  243   
75075   94   71  177  116  235   21   49   92  107    5  ...   39    2  251   

        25   26   27   28   29   30   31  
0      220  101  127  236   60  204   47  
1      222  229  243  252  220   12  111  
2      222  101  247  174  254  140   39  
3      219  101  127  174   62  206   39  
4      222  229  255  254  214  132   44  
...    ...  ...  ...  ...  ...  ...  ...  
75071  212  101   74  250   85   65  123  
75072  222  241  226  255   69   64   45  
75073  150  173  211   56   62   36  249  
75074  108   85  228   23  215  157   44  
75075  150   58  215  170   43   52  184  

[75076 rows x 32 columns]

In [ ]:
#Applying FAST + BRIEF Feature descriptor on folder2
i=0
for filename in os.listdir(folder2):
    
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder2.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (58, 32)
descriptor shape  1  :  (105, 32)
descriptor shape  2  :  (23, 32)
descriptor shape  3  :  (89, 32)
descriptor shape  4  :  (22, 32)
descriptor shape  5  :  (6, 32)
descriptor shape  6  :  (26, 32)
descriptor shape  7  :  (39, 32)
descriptor shape  8  :  (216, 32)
descriptor shape  9  :  (221, 32)
descriptor shape  10  :  (109, 32)
descriptor shape  11  :  (152, 32)
descriptor shape  12  :  (166, 32)
descriptor shape  13  :  (168, 32)
descriptor shape  14  :  (250, 32)
descriptor shape  15  :  (10, 32)
descriptor shape  16  :  (7, 32)
descriptor shape  17  :  (100, 32)
descriptor shape  18  :  (4, 32)
descriptor shape  19  :  (69, 32)
descriptor shape  20  :  (34, 32)
descriptor shape  21  :  (32, 32)
descriptor shape  22  :  (28, 32)
descriptor shape  23  :  (3, 32)
descriptor shape  24  :  (130, 32)
descriptor shape  25  :  (86, 32)
descriptor shape  26  :  (65, 32)
descriptor shape  27  :  (38, 32)
descriptor shape  28  :  (27, 32)
descriptor shape  

In [ ]:
#reading previously saved feature descriptor csv file of folder2 and save it into a dataframe
data2= pd.read_csv('folder2.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       92  115  208  151  187  158   31  229  229  134  ...   54   39  227   
1      113   69  196   94  168  186  177  204   53   46  ...   86  147  233   
2       50   87  120  221   41  202  113  212  149  254  ...  255  117   37   
3      179   63  184  201  153  200   53  222  134   82  ...  251   52  112   
4       50   23   56  207   59  202  151  253  148   82  ...  251  181   68   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
73253   31    7  184  197  168  137  177  157  228   90  ...  247    0  243   
73254  224  106   77  186   31   54   94  111   24  229  ...    8  254   13   
73255   73    8   76  184   55  182  126   43   25  211  ...  136  252   13   
73256   74    8   68  191   23   54   86   41   25  247  ...  128   62   12   
73257   52  117  111  137   12  232   69  155  162  175  ...   67   24   17   

        25   26   27   28   29   30   31  
0      145   61  167  218   37  238  114  
1      209   13  227  184  111  206   55  
2       11  172   98  249  103   64   55  
3       14  229  194  243  151  137  186  
4      174  229  227  126    5  232  252  
...    ...  ...  ...  ...  ...  ...  ...  
73253  220  181  198  184   71   88   42  
73254  129  206   57  210  104  134  247  
73255  161  204   40   70  120  162  247  
73256  163  236   59  108  104  226  243  
73257  204  103  106  249  217   81  107  

[73258 rows x 32 columns]

In [ ]:
#append all the class wise feature descriptor data into one data frame
data=data1.append(data2)
data

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0      177   55   46    0   47  114  197   28   54  251  ...  201  168  217   
1      177   55   60   72   47  114  197  156   22  251  ...  221  168  185   
2      177   55   30    2   45   82  197   28  116  251  ...  217  168  169   
3      177  183   22   34   47  114  229   12   54  243  ...  201  168  201   
4      177   55   62   96   43   66  197  156   54  251  ...  205  168  185   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
73253   31    7  184  197  168  137  177  157  228   90  ...  247    0  243   
73254  224  106   77  186   31   54   94  111   24  229  ...    8  254   13   
73255   73    8   76  184   55  182  126   43   25  211  ...  136  252   13   
73256   74    8   68  191   23   54   86   41   25  247  ...  128   62   12   
73257   52  117  111  137   12  232   69  155  162  175  ...   67   24   17   

        25   26   27   28   29   30   31  
0      220  101  127  236   60  204   47  
1      222  229  243  252  220   12  111  
2      222  101  247  174  254  140   39  
3      219  101  127  174   62  206   39  
4      222  229  255  254  214  132   44  
...    ...  ...  ...  ...  ...  ...  ...  
73253  220  181  198  184   71   88   42  
73254  129  206   57  210  104  134  247  
73255  161  204   40   70  120  162  247  
73256  163  236   59  108  104  226  243  
73257  204  103  106  249  217   81  107  

[148334 rows x 32 columns]

In [ ]:
#save appended data into a csv file
csv_data=data.to_csv('finalData.csv', mode='a', header=False,index=False)

In [ ]:
#read the data from the previously saved csv file
data = pd.read_csv('finalData.csv',header=None)
data

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       177   55   46    0   47  114  197   28   54  251  ...  201  168  217   
1       177   55   60   72   47  114  197  156   22  251  ...  221  168  185   
2       177   55   30    2   45   82  197   28  116  251  ...  217  168  169   
3       177  183   22   34   47  114  229   12   54  243  ...  201  168  201   
4       177   55   62   96   43   66  197  156   54  251  ...  205  168  185   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
148329   31    7  184  197  168  137  177  157  228   90  ...  247    0  243   
148330  224  106   77  186   31   54   94  111   24  229  ...    8  254   13   
148331   73    8   76  184   55  182  126   43   25  211  ...  136  252   13   
148332   74    8   68  191   23   54   86   41   25  247  ...  128   62   12   
148333   52  117  111  137   12  232   69  155  162  175  ...   67   24   17   

         25   26   27   28   29   30   31  
0       220  101  127  236   60  204   47  
1       222  229  243  252  220   12  111  
2       222  101  247  174  254  140   39  
3       219  101  127  174   62  206   39  
4       222  229  255  254  214  132   44  
...     ...  ...  ...  ...  ...  ...  ...  
148329  220  181  198  184   71   88   42  
148330  129  206   57  210  104  134  247  
148331  161  204   40   70  120  162  247  
148332  163  236   59  108  104  226  243  
148333  204  103  106  249  217   81  107  

[148334 rows x 32 columns]

## Dimensionality Reduction

### Kmeans

In [ ]:
#Applying Kmeans
kmeans = KMeans(n_clusters=2)
kmeans.fit(data)

KMeans(n_clusters=2)

In [ ]:
#save the model to disk
import pickle
filename = 'Kmeans_CL_2_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [ ]:
#calculate histogram of trained kmeans
hist = np.histogram(kmeans.labels_,bins=[0,1,2])

print("Histogram of trained kmeans")
print(hist, "\n")

Histogram of trained kmeans
(array([65564, 82770], dtype=int64), array([0, 1, 2])) 



In [ ]:
#performing kmeans prediction on the folder1 with the pretrained kmeans model

#initialising i=0; as it is the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2])
    
    #append the dataframe into the array 
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder1.csv', mode='a',header=False,index=False)

In [ ]:
#performing kmeans prediction on the folder2 with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(200,200)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2])
    #append the dataframe into the array 
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder2.csv', mode='a',header=False,index=False)

102.png
105.png
106.png
110.png
114.png
119.png
130.png
131.png
136.png
138.png
139.png
141.png
142.png
144.png
148.png
157.png
158.png
159.png
167.png
170.png
175.png
190.png
205.png
206.png
208.png
212.png
218.png
221.png
224.png
227.png
255.png
257.png
272.png
273.png
35.png
471.png
477.png
48.png
513.png
514.png
524.png
526.png
535.png
546.png
56.png
59.png
6.png
632.png
639.png
677.png
701.png
719.png
758.png
759.png
760.png
814.png
825.png
826.png
827.png
829.png
832.png
885.png
89.png
939.png
956.png
959.png
96.png
97.png
978.png


In [ ]:
#Displaying the kmeans predicted data of folder1
print("Broken Chair")
dat1= pd.read_csv('finalFolder1.csv',header=None)
print(dat1)

Broken Chair
       0    1  2
0     29  104  0
1     16   44  0
2     22   52  0
3     30   36  0
4     21   46  0
...   ..  ... ..
1047  41   46  0
1048  38   59  0
1049  34   56  0
1050  12   14  0
1051  39   41  0

[1052 rows x 3 columns]


In [ ]:
#Displaying the kmeans predicted data of folder2
print("Normal Chair")
dat2= pd.read_csv('finalFolder2.csv',header=None)
print(dat2)

Normal Chair
      0   1  2
0     2   1  1
1    10   5  1
2     2   2  1
3     3   5  1
4     3   2  1
..   ..  .. ..
995   9  11  1
996   1   5  1
997   9  10  1
998   3   1  1
999   2  13  1

[1000 rows x 3 columns]


In [ ]:
#appending All kmeans predicted data into 1 dataframe
A = dat1.append(dat2)

In [ ]:
#save the predicted data into csv file
csv_data=A.to_csv('FinalF.csv', mode='a',header=False,index=False)

In [ ]:
#read the data from the previously saved csv file
A = pd.read_csv("FinalF.csv",header=None)
A

0    1  2
0     29  104  0
1     16   44  0
2     22   52  0
3     30   36  0
4     21   46  0
...   ..  ... ..
2047   9   11  1
2048   1    5  1
2049   9   10  1
2050   3    1  1
2051   2   13  1

[2052 rows x 3 columns]

In [ ]:
#assigning x the columns from 0 & 1 for training
x = A.iloc[:,0:2].values
x
#performing Normalization 
from sklearn import preprocessing
a=preprocessing.normalize(x, axis=0)
scaled_df= pd.DataFrame(a)
x=scaled_df

In [ ]:
#assigning y with the column 2 as target variable
y = A.iloc[:,2].values
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [ ]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [ ]:
Dhoni

array([[-0.02392592,  0.08498839],
       [-0.03182816, -0.00509383],
       [-0.02818097,  0.00691713],
       ...,
       [-0.03608321, -0.05614042],
       [-0.03973039, -0.06965276],
       [-0.04033826, -0.05163631]])

### LDA

In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [ ]:
lda = LDA(n_components=None)

In [ ]:
Bhumi = lda.fit_transform(Dhoni, y)
Bhumi

array([[-1.13055598],
       [-0.27939407],
       [-0.3658136 ],
       ...,
       [ 0.20525723],
       [ 0.30723738],
       [ 0.11416577]])

In [ ]:
Bhumi = pd.DataFrame(Bhumi)
Bhumi

0
0    -1.130556
1    -0.279394
2    -0.365814
3    -0.066090
4    -0.278794
...        ...
2047  0.189697
2048  0.232306
2049  0.205257
2050  0.307237
2051  0.114166

[2052 rows x 1 columns]

In [ ]:
Bhumi.shape

(2052, 1)

In [ ]:
print(lda.explained_variance_ratio_) 

[1.]


In [ ]:
lda = LDA(n_components=1)
lda.fit_transform(Dhoni, y)

array([[-1.13055598],
       [-0.27939407],
       [-0.3658136 ],
       ...,
       [ 0.20525723],
       [ 0.30723738],
       [ 0.11416577]])

In [ ]:
# save the model to disk
import pickle

filename = 'LDA_1_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [ ]:
Bhumi = lda.fit_transform(Dhoni, y)
Bhumi

array([[-1.13055598],
       [-0.27939407],
       [-0.3658136 ],
       ...,
       [ 0.20525723],
       [ 0.30723738],
       [ 0.11416577]])

In [ ]:
Bhumi.shape

(2052, 1)

In [ ]:
print(lda.explained_variance_ratio_) 

[1.]


In [ ]:
Bhumi = pd.DataFrame(Bhumi)
Bhumi

0
0    -1.130556
1    -0.279394
2    -0.365814
3    -0.066090
4    -0.278794
...        ...
2047  0.189697
2048  0.232306
2049  0.205257
2050  0.307237
2051  0.114166

[2052 rows x 1 columns]

In [ ]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)
B

0  0
0    -1.130556  0
1    -0.279394  0
2    -0.365814  0
3    -0.066090  0
4    -0.278794  0
...        ... ..
2047  0.189697  1
2048  0.232306  1
2049  0.205257  1
2050  0.307237  1
2051  0.114166  1

[2052 rows x 2 columns]

In [ ]:
csv_data=B.to_csv('FinalLDAFV.csv', mode='a',header=False,index=False)

In [ ]:
data= pd.read_csv('FinalLDAFV.csv',header=None)

data

0  1
0    -1.130556  0
1    -0.279394  0
2    -0.365814  0
3    -0.066090  0
4    -0.278794  0
...        ... ..
2047  0.189697  1
2048  0.232306  1
2049  0.205257  1
2050  0.307237  1
2051  0.114166  1

[2052 rows x 2 columns]

In [ ]:
x = data.iloc[:,0:1].values
print("X values")
print(x)

y = data.iloc[:,1]
print("Y values")
print(y)

X values
[[-1.13055598]
 [-0.27939407]
 [-0.3658136 ]
 ...
 [ 0.20525723]
 [ 0.30723738]
 [ 0.11416577]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
2047    1
2048    1
2049    1
2050    1
2051    1
Name: 1, Length: 2052, dtype: int64


In [ ]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

## Classifiers

### Decision Tree

In [ ]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

Decision Tree Results
Decision Tree Accuracy:  89.78102189781022 %


In [ ]:
# Performance Metrics
print(metrics.confusion_matrix(y_test, y_pred1))
print(metrics.classification_report(y_test, y_pred1))

[[190  31]
 [ 11 179]]
              precision    recall  f1-score   support

           0       0.95      0.86      0.90       221
           1       0.85      0.94      0.89       190

    accuracy                           0.90       411
   macro avg       0.90      0.90      0.90       411
weighted avg       0.90      0.90      0.90       411



In [ ]:
#print(model1.predict(x_test))
#print(model1.predict_proba(x_test))
labels = model1.predict(x_test)
probs = model1.predict_proba(x_test)
# print(probs)
print(len(labels))
mis_class = []
for i in range(len(labels)):
    if probs[i][0] < 0.2:
        print(np.where(probs[i] == max(probs[i])))
        mis_class.append(labels[i])
#         print(labels[i])

print(len(mis_class))

411
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64),)
(array([1], dtype=int64)

### SVM (OVR)

### SVM (OVR) RBF

In [ ]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [ ]:
filename = 'SVC_RBF_LDA.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [ ]:
Dhoni_LK

SVC()

In [ ]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [ ]:
y_pred_LK

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
# Confusion Matrix
confusion_matrix(y_test, y_pred_LK)

array([[175,  46],
       [  7, 183]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("SVM RBF Results")
print("SVM RBF Accuracy: ",accuracy_score(y_test, y_pred_LK)*100,"%")

SVM RBF Results
SVM RBF Accuracy:  87.10462287104623 %


In [ ]:
# Performance Metrics
from sklearn import metrics

print(metrics.classification_report(y_test, y_pred_LK))

              precision    recall  f1-score   support

           0       0.96      0.79      0.87       221
           1       0.80      0.96      0.87       190

    accuracy                           0.87       411
   macro avg       0.88      0.88      0.87       411
weighted avg       0.89      0.87      0.87       411



### SVM (OVR) Linear

In [ ]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='linear')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [ ]:
filename = 'SVC_linear_LDA.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [ ]:
Dhoni_LK

SVC(kernel='linear')

In [ ]:
y_pred_LK = Dhoni_LK.predict(x_test)

y_pred_LK

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
# Confusion Matrix
confusion_matrix(y_test, y_pred_LK)

array([[163,  58],
       [  1, 189]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("SVM linear Results")
print("SVM linear Accuracy: ",accuracy_score(y_test, y_pred_LK)*100,"%")

SVM linear Results
SVM linear Accuracy:  85.64476885644768 %


In [ ]:
# Performance Metrics
from sklearn import metrics

print(metrics.classification_report(y_test, y_pred_LK))

              precision    recall  f1-score   support

           0       0.99      0.74      0.85       221
           1       0.77      0.99      0.86       190

    accuracy                           0.86       411
   macro avg       0.88      0.87      0.86       411
weighted avg       0.89      0.86      0.86       411



## SVM (OVO) 

### SVM (OVO) RBF

In [ ]:
#RBF
rbf = svm.SVC(kernel='rbf', gamma=1, C=1, decision_function_shape='ovo').fit(x_train, y_train)

In [ ]:
filename = 'SVC(OVO)_rbf_LDA.sav'
pickle.dump(rbf, open(filename, 'wb'))

In [ ]:
rbf

SVC(C=1, decision_function_shape='ovo', gamma=1)

In [ ]:
y_pred = rbf.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
# Confusion Matrix
confusion_matrix(y_test, y_pred)

array([[174,  47],
       [  7, 183]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("SVM (OVO) RBF Results")
print("SVM (OVO) RBF Accuracy: ",accuracy_score(y_test, y_pred)*100,"%")

SVM (OVO) RBF Results
SVM (OVO) RBF Accuracy:  86.86131386861314 %


In [ ]:
# Performance Metrics
from sklearn import metrics

print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.96      0.79      0.87       221
           1       0.80      0.96      0.87       190

    accuracy                           0.87       411
   macro avg       0.88      0.88      0.87       411
weighted avg       0.88      0.87      0.87       411



### SVM (OVO) Linear

In [ ]:
#Linear function
linear = svm.SVC(kernel='linear', C=1, decision_function_shape='ovo').fit(x_train, y_train)

In [ ]:
filename = 'SVC(OVO)_linear_LDA.sav'
pickle.dump(linear, open(filename, 'wb'))

In [ ]:
linear

SVC(C=1, decision_function_shape='ovo', kernel='linear')

In [ ]:
y_pred = linear.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
# Confusion Matrix
confusion_matrix(y_test, y_pred)

array([[163,  58],
       [  1, 189]], dtype=int64)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
print("SVM (OVO) Linear Results")
print("SVM (OVO) Linear Accuracy: ",accuracy_score(y_test, y_pred)*100,"%")

SVM (OVO) Linear Results
SVM (OVO) Linear Accuracy:  85.64476885644768 %


In [ ]:
# Performance Metrics
from sklearn import metrics

print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.74      0.85       221
           1       0.77      0.99      0.86       190

    accuracy                           0.86       411
   macro avg       0.88      0.87      0.86       411
weighted avg       0.89      0.86      0.86       411



### Random Forest 

In [ ]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='log2',
                                max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, 
                                n_jobs=None, random_state=2, verbose=0, warm_start=False, class_weight=None, 
                                ccp_alpha=0.0, max_samples=None)
filename = 'model4.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
#Results
print("RandomF Results")
print("RandomF Accuracy: ",accuracy_score(y_test, y_pred4)*100,"%")

RandomF Results
RandomF Accuracy:  89.05109489051095 %


In [ ]:
# Performance Metrics
from sklearn import metrics

print(metrics.confusion_matrix(y_test, y_pred4))
print(metrics.classification_report(y_test, y_pred4))

[[189  32]
 [ 13 177]]
              precision    recall  f1-score   support

           0       0.94      0.86      0.89       221
           1       0.85      0.93      0.89       190

    accuracy                           0.89       411
   macro avg       0.89      0.89      0.89       411
weighted avg       0.89      0.89      0.89       411



###  k-nearest neighbors

In [ ]:
#KNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

# Loading data 
data= pd.read_csv('FinalLDAFV.csv',header=None)
 
# Create feature and target arrays

X = data.iloc[:,0:1].values

y = data.iloc[:,1]

 
# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
 
knn = KNeighborsClassifier(n_neighbors=7)
     
knn.fit(X_train, y_train)
knn.fit(X_test, y_test) 
y_pred = knn.predict(X_test)

# Calculate the accuracy of the model
print("KNN Results")
print("KNN Accuracy: ",knn.score(X_test, y_test)*100,"%")

KNN Results
KNN Accuracy:  88.56447688564477 %


In [ ]:
# Save the trained model as a pickle string.
import pickle
 
saved_model = pickle.dumps(knn)

In [ ]:
# Performance Metrics
from sklearn import metrics

print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[171  33]
 [ 14 193]]
              precision    recall  f1-score   support

           0       0.92      0.84      0.88       204
           1       0.85      0.93      0.89       207

    accuracy                           0.89       411
   macro avg       0.89      0.89      0.89       411
weighted avg       0.89      0.89      0.89       411



## Recognition

In [ ]:
#Assigning path with any any class image
data=[]
path="C:/Users/Mahesh/ML Project/Dataset/Normal Chair/75.png"


#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
    
#resize image
resize=(500,500)
img=cv2.resize(a,resize)
    
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Initiate FAST detector
star = cv2.xfeatures2d.StarDetector_create()
# Initiate BRIEF extractor
brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
# find the keypoints with STAR
kp = star.detect(img, None)
# compute the descriptors with BRIEF
keypoints, descriptors = brief.compute(gray, kp)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (35, 32)
Histogram:
     0   1
0  17  18


In [ ]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [ ]:
Mukta

array([[0., 0.]])

In [ ]:
Mukta.shape

(1, 2)

In [ ]:
MB = lda.transform(Mukta)

In [ ]:
MB.shape

(1, 1)

In [ ]:
MB

array([[9.11041072e-16]])

In [ ]:
knn_from_pickle = pickle.loads(saved_model)

In [ ]:
output=knn_from_pickle.predict(MB)
print(output)

[0]


In [ ]:
pred= model4.predict(MB)
print(pred)

[1]


In [ ]:
import pyttsx3
engineio = pyttsx3.init()

In [ ]:
if(output==0):
    engineio.say("Broken Chair")
    engineio.runAndWait() #voice output
if(output==1):
    engineio.say("Normal Chair")
    engineio.runAndWait() #voice output   

In [ ]:
MuktaS = StandardScaler()

In [ ]:
#Applying FAST + BRIEF Feature descriptor on folder1
i=0
for filename in os.listdir(folder1):
    data=[]
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    #print("descriptor shape ",i," : ", out.shape)
    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2])

    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])

    Output = pd.DataFrame(data)
    Mukta = MuktaS.fit_transform(Output)
    MB = lda.transform(Mukta)
    pred= model4.predict(MB)
    print(i, " = ", pred)
    
    i=i+1
  

0  =  [1]
1  =  [1]
2  =  [1]
3  =  [1]
4  =  [1]
5  =  [1]
6  =  [1]
7  =  [1]
8  =  [1]
9  =  [1]
10  =  [1]
11  =  [1]
12  =  [1]
13  =  [1]
14  =  [1]
15  =  [1]
16  =  [1]
17  =  [1]
18  =  [1]
19  =  [1]
20  =  [1]
21  =  [1]
22  =  [1]
23  =  [1]
24  =  [1]
25  =  [1]
26  =  [1]
27  =  [1]
28  =  [1]
29  =  [1]
30  =  [1]
31  =  [1]
32  =  [1]
33  =  [1]
34  =  [1]
35  =  [1]
36  =  [1]
37  =  [1]
38  =  [1]
39  =  [1]
40  =  [1]
41  =  [1]
42  =  [1]
43  =  [1]
44  =  [1]
45  =  [1]
46  =  [1]
47  =  [1]
48  =  [1]
49  =  [1]
50  =  [1]
51  =  [1]
52  =  [1]
53  =  [1]
54  =  [1]
55  =  [1]
56  =  [1]
57  =  [1]
58  =  [1]
59  =  [1]
60  =  [1]
61  =  [1]
62  =  [1]
63  =  [1]
64  =  [1]
65  =  [1]
66  =  [1]
67  =  [1]
68  =  [1]
69  =  [1]
70  =  [1]
71  =  [1]
72  =  [1]
73  =  [1]
74  =  [1]
75  =  [1]
76  =  [1]
77  =  [1]
78  =  [1]
79  =  [1]
80  =  [1]
81  =  [1]
82  =  [1]
83  =  [1]
84  =  [1]
85  =  [1]
86  =  [1]
87  =  [1]
88  =  [1]
89  =  [1]
90  =  [1]
91  =  [1

In [ ]:
#Applying FAST + BRIEF Feature descriptor on folder1
i=0
for filename in os.listdir(folder2):
    data=[]
    #path
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    #print("descriptor shape ",i," : ", out.shape)
    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)

    #get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the hostogram for all those vlaues
    hist=np.histogram(a,bins=[0,1,2])

    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])

    Output = pd.DataFrame(data)
    Mukta = MuktaS.fit_transform(Output)
    MB = lda.transform(Mukta)
    pred= model4.predict(MB)
    print(i, " = ", pred)
    
    i=i+1
  

0  =  [1]
1  =  [1]
2  =  [1]
3  =  [1]
4  =  [1]
5  =  [1]
6  =  [1]
7  =  [1]
8  =  [1]
9  =  [1]
10  =  [1]
11  =  [1]
12  =  [1]
13  =  [1]
14  =  [1]
15  =  [1]
16  =  [1]
17  =  [1]
18  =  [1]
19  =  [1]
20  =  [1]
21  =  [1]
22  =  [1]
23  =  [1]
24  =  [1]
25  =  [1]
26  =  [1]
27  =  [1]
28  =  [1]
29  =  [1]
30  =  [1]
31  =  [1]
32  =  [1]
33  =  [1]
34  =  [1]
35  =  [1]
36  =  [1]
37  =  [1]
38  =  [1]
39  =  [1]
40  =  [1]
41  =  [1]
42  =  [1]
43  =  [1]
44  =  [1]
45  =  [1]
46  =  [1]
47  =  [1]
48  =  [1]
49  =  [1]
50  =  [1]
51  =  [1]
52  =  [1]
53  =  [1]
54  =  [1]
55  =  [1]
56  =  [1]
57  =  [1]
58  =  [1]
59  =  [1]
60  =  [1]
61  =  [1]
62  =  [1]
63  =  [1]
64  =  [1]
65  =  [1]
66  =  [1]
67  =  [1]
68  =  [1]
69  =  [1]
70  =  [1]
71  =  [1]
72  =  [1]
73  =  [1]
74  =  [1]
75  =  [1]
76  =  [1]
77  =  [1]
78  =  [1]
79  =  [1]
80  =  [1]
81  =  [1]
82  =  [1]
83  =  [1]
84  =  [1]
85  =  [1]
86  =  [1]
87  =  [1]
88  =  [1]
89  =  [1]
90  =  [1]
91  =  [1

ValueError: Found array with 0 sample(s) (shape=(0, 0)) while a minimum of 1 is required by KMeans.