In [1]:
#Required libraries
import numpy as np
import pandas as pd                               
import os
import csv
import cv2
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn import svm, datasets
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn import preprocessing

In [2]:
#Path of positive dataset
folder1='Dataset/Fridge'
folder2='Dataset/Gas Stove'
folder3='Dataset/Induction'
folder4='Dataset/Microwave Oven'
folder5='Dataset/Mixer'
folder6='Dataset/Water Filter'

In [3]:
#Applying SIFT descriptor on folder1
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500, 500)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
  
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder1.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (83, 32)
descriptor shape  1  :  (119, 32)
descriptor shape  2  :  (46, 32)
descriptor shape  3  :  (97, 32)
descriptor shape  4  :  (138, 32)
descriptor shape  5  :  (31, 32)
descriptor shape  6  :  (50, 32)
descriptor shape  7  :  (140, 32)
descriptor shape  8  :  (74, 32)
descriptor shape  9  :  (118, 32)
descriptor shape  10  :  (65, 32)
descriptor shape  11  :  (124, 32)
descriptor shape  12  :  (67, 32)
descriptor shape  13  :  (91, 32)
descriptor shape  14  :  (119, 32)
descriptor shape  15  :  (99, 32)
descriptor shape  16  :  (80, 32)
descriptor shape  17  :  (244, 32)
descriptor shape  18  :  (155, 32)
descriptor shape  19  :  (42, 32)
descriptor shape  20  :  (167, 32)
descriptor shape  21  :  (134, 32)
descriptor shape  22  :  (189, 32)
descriptor shape  23  :  (98, 32)
descriptor shape  24  :  (185, 32)
descriptor shape  25  :  (108, 32)
descriptor shape  26  :  (98, 32)
descriptor shape  27  :  (140, 32)
descriptor shape  28  :  (169, 32)
descripto

In [4]:
#reading previously saved feature descriptor csv file of folder1 and save it into a dataframe
data1 = pd.read_csv('folder1.csv',header=None,dtype='uint8')
data1=data1.astype(np.uint8) 
data1

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0        79  139  177  196  161  157   41  253  207   20  ...   62   67  243   
1        76  197  192  116  233  183   57  196   93    4  ...  190   98  175   
2        78  206  145   52  231   23  178  101   73    4  ...   60   46  249   
3        78  143  177   55  205   13  201  213   74  132  ...   47  107  233   
4        76   78  133   38  239   39  185  236   74  132  ...   14   42  237   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
300841  228  121  215  147  219  214   79   43  253  173  ...   32  222    3   
300842   79    9  249   68  243  148   59  184  229   21  ...   38   18  115   
300843  230  234  144   82  243  214   58  102  205   20  ...   60  215  230   
300844  228  250   69   58  115  246   62  106   25  197  ...    8  223   47   
300845  207  200  147  145  214   21  222   35  105  165  ...   48  199   70   

         25   26   27   28   29   30   31  
0        49   28  133   24   23  191  176  
1        33  152  198  136   47   62  133  
2        49   56   23   40   40   63  210  
3       114   26   95   75   17  239    2  
4        49  122   91   57   88  143  243  
...     ...  ...  ...  ...  ...  ...  ...  
300841   99   90   12    3  202  210  212  
300842  166   59    6   54   95   49  184  
300843   33  156  133    0  162   63  144  
300844   33  138  148    0  168  190  212  
300845   39   27   28   71  162  243  130  

[300846 rows x 32 columns]

In [5]:
#Applying SIFT descriptor on folder2
i=0
for filename in os.listdir(folder2):
    
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder2.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (294, 32)
descriptor shape  1  :  (456, 32)
descriptor shape  2  :  (91, 32)
descriptor shape  3  :  (142, 32)
descriptor shape  4  :  (67, 32)
descriptor shape  5  :  (345, 32)
descriptor shape  6  :  (201, 32)
descriptor shape  7  :  (319, 32)
descriptor shape  8  :  (260, 32)
descriptor shape  9  :  (337, 32)
descriptor shape  10  :  (156, 32)
descriptor shape  11  :  (298, 32)
descriptor shape  12  :  (247, 32)
descriptor shape  13  :  (361, 32)
descriptor shape  14  :  (108, 32)
descriptor shape  15  :  (314, 32)
descriptor shape  16  :  (267, 32)
descriptor shape  17  :  (359, 32)
descriptor shape  18  :  (242, 32)
descriptor shape  19  :  (159, 32)
descriptor shape  20  :  (227, 32)
descriptor shape  21  :  (293, 32)
descriptor shape  22  :  (280, 32)
descriptor shape  23  :  (543, 32)
descriptor shape  24  :  (385, 32)
descriptor shape  25  :  (301, 32)
descriptor shape  26  :  (237, 32)
descriptor shape  27  :  (249, 32)
descriptor shape  28  :  (418, 3

In [6]:
#reading previously saved feature descriptor csv file of folder2 and save it into a dataframe
data2= pd.read_csv('folder2.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0        78   86  167   38  227   22  182  108  107  133  ...   36  110   40   
1       185   55   46  127   10   50  173  220   50  242  ...  217  160  137   
2       185   55   46  127   10   50  229  220   50  242  ...  201  160  137   
3        25    4   76  236   44   43  192  209   50  242  ...  203   40  221   
4        25    4   76  236   47   34  220  201   33  195  ...  202   40  221   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
738643   27    5   42  141   12  137  197  157   34  178  ...  227   34  201   
738644   25    6   46  255   12   59  197   17   51  250  ...  201   56   76   
738645   57  134  110  173   12   43  196   19  178  251  ...  193  153   92   
738646  231   57  176  210  179  212   63  239  229   19  ...   62   23  227   
738647   27    7   48   68  168    9  169  220  118   18  ...  255   32  249   

         25   26   27   28   29   30   31  
0       178  138   23   10    8  166  208  
1       222  165  115  252   85  204  111  
2       222  165  115  186   94  204   39  
3       252  101  123  127   93  192  109  
4       220  229  106  254   93  128  251  
...     ...  ...  ...  ...  ...  ...  ...  
738643  220  103  106  255   93  193  107  
738644  222  165  123  239   93  192  111  
738645  222  231  123  239  125  192   79  
738646  167   61  132   22  183  189  176  
738647  220   33  243  186   95   12   45  

[738648 rows x 32 columns]

In [7]:
#Applying SIFT descriptor on folder3
i=0
for filename in os.listdir(folder3):
    
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder3.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (130, 32)
descriptor shape  1  :  (306, 32)
descriptor shape  2  :  (158, 32)
descriptor shape  3  :  (30, 32)
descriptor shape  4  :  (126, 32)
descriptor shape  5  :  (100, 32)
descriptor shape  6  :  (137, 32)
descriptor shape  7  :  (114, 32)
descriptor shape  8  :  (85, 32)
descriptor shape  9  :  (172, 32)
descriptor shape  10  :  (52, 32)
descriptor shape  11  :  (130, 32)
descriptor shape  12  :  (235, 32)
descriptor shape  13  :  (107, 32)
descriptor shape  14  :  (84, 32)
descriptor shape  15  :  (172, 32)
descriptor shape  16  :  (147, 32)
descriptor shape  17  :  (89, 32)
descriptor shape  18  :  (160, 32)
descriptor shape  19  :  (236, 32)
descriptor shape  20  :  (78, 32)
descriptor shape  21  :  (162, 32)
descriptor shape  22  :  (158, 32)
descriptor shape  23  :  (93, 32)
descriptor shape  24  :  (99, 32)
descriptor shape  25  :  (214, 32)
descriptor shape  26  :  (109, 32)
descriptor shape  27  :  (165, 32)
descriptor shape  28  :  (201, 32)
des

In [8]:
#reading previously saved feature descriptor csv file of folder3 and save it into a dataframe
data3= pd.read_csv('folder3.csv',header=None,dtype='uint8')
data3=data3.astype(np.uint8)
data3

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       179   37  124   75   14   64  213  153   34  242  ...  235  176  145   
1        17   77    9   16   24    0  209  218   32    2  ...   65  150    5   
2         8    6    0   52   37    1  136   68    0    0  ...  128   40  201   
3        24    6   44  252   47   51   68   89   19  211  ...  201   40  205   
4        25   22  108  220   44  186   84  137  177  194  ...  201   56  220   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
477778  169  254    7   46   67   33  214  100   51  226  ...    8  165  140   
477779  177  102   14  237   12   43  204  205   50  166  ...  205  168  156   
477780   76   71  165  116  236   47  169  220  106    4  ...  238   42  251   
477781   27  158    4  253    5   41  196   85   19  210  ...  201   41  221   
477782   95   23  176  116  233   25  169  220  105   82  ...  255   34  249   

         25   26   27   28   29   30   31  
0       220  229   98  254  223  129  120  
1       172  231   81   55   84  129  232  
2       144   32   91   40    0   12  114  
3       216  165  122  232  104   68  247  
4       221  165  250  252  124  196  255  
...     ...  ...  ...  ...  ...  ...  ...  
477778  255  231   51  173   60  175  150  
477779  220  228  123  254   72   72  103  
477780  240  120   95   58   74   27   59  
477781  159  229  123  237   33  109   91  
477782  182   57  215   59   69   44  188  

[477783 rows x 32 columns]

In [9]:
#Applying SIFT descriptor on folder4
i=0
for filename in os.listdir(folder4):
    
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder4.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (48, 32)
descriptor shape  1  :  (169, 32)
descriptor shape  2  :  (32, 32)
descriptor shape  3  :  (8, 32)
descriptor shape  4  :  (15, 32)
descriptor shape  5  :  (34, 32)
descriptor shape  6  :  (47, 32)
descriptor shape  7  :  (35, 32)
descriptor shape  8  :  (6, 32)
descriptor shape  9  :  (67, 32)
descriptor shape  10  :  (6, 32)
descriptor shape  11  :  (6, 32)
descriptor shape  12  :  (0, 0)
descriptor shape  13  :  (45, 32)
descriptor shape  14  :  (62, 32)
descriptor shape  15  :  (70, 32)
descriptor shape  16  :  (24, 32)
descriptor shape  17  :  (37, 32)
descriptor shape  18  :  (20, 32)
descriptor shape  19  :  (66, 32)
descriptor shape  20  :  (31, 32)
descriptor shape  21  :  (38, 32)
descriptor shape  22  :  (29, 32)
descriptor shape  23  :  (102, 32)
descriptor shape  24  :  (69, 32)
descriptor shape  25  :  (75, 32)
descriptor shape  26  :  (55, 32)
descriptor shape  27  :  (192, 32)
descriptor shape  28  :  (23, 32)
descriptor shape  29  :  (1

In [10]:
#reading previously saved feature descriptor csv file of folder4 and save it into a dataframe
data4= pd.read_csv('folder4.csv',header=None,dtype='uint8')
data4=data4.astype(np.uint8)
data4

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0        79  142  145  151  193   29  146  101  107    4  ...   48   98  233   
1       206  254  145  165  195    5  219  237   76    4  ...   48  230  205   
2        78   74  144  183  163   23   54  109  105  133  ...   60   46  200   
3       239   43  149   58  203    6  251  236   72  132  ...    2  135   25   
4       207   47  145   38  235    4  187  236   72   20  ...   34   39  173   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
243673   78  203  145  116  227   23   58  100  109    4  ...   62   71  251   
243674   78   78  149  191  151   22   94   45    9  165  ...   32   46   77   
243675  180  248  127   25   82  240   74   18  188  237  ...   85  214   22   
243676   95    7  176  100  169    9  161  220   98   16  ...  255   34  249   
243677   76  206  133  182  165   63  140  229   73  132  ...  138   43  205   

         25   26   27   28   29   30   31  
0        55   27   81   79   48  251  130  
1        55  218  149   93   16  251  146  
2        51  184   31   40   40  118  210  
3        87  106  151  157   25  191  220  
4        55  250  149   29   25  191  152  
...     ...  ...  ...  ...  ...  ...  ...  
243673   49   24  151   10   34   63  176  
243674   49  174   27   76   56  227  210  
243675  106  146  172  195  226   82   12  
243676  180  125  211   59   71   13   57  
243677  177   60   91  127   40  175  243  

[243678 rows x 32 columns]

In [11]:
#Applying SIFT descriptor on folder5
i=0
for filename in os.listdir(folder5):
    
    path=os.path.join(folder5,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder5.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (34, 32)
descriptor shape  1  :  (40, 32)
descriptor shape  2  :  (25, 32)
descriptor shape  3  :  (41, 32)
descriptor shape  4  :  (52, 32)
descriptor shape  5  :  (50, 32)
descriptor shape  6  :  (61, 32)
descriptor shape  7  :  (65, 32)
descriptor shape  8  :  (19, 32)
descriptor shape  9  :  (82, 32)
descriptor shape  10  :  (74, 32)
descriptor shape  11  :  (101, 32)
descriptor shape  12  :  (51, 32)
descriptor shape  13  :  (58, 32)
descriptor shape  14  :  (62, 32)
descriptor shape  15  :  (65, 32)
descriptor shape  16  :  (14, 32)
descriptor shape  17  :  (35, 32)
descriptor shape  18  :  (40, 32)
descriptor shape  19  :  (49, 32)
descriptor shape  20  :  (80, 32)
descriptor shape  21  :  (26, 32)
descriptor shape  22  :  (15, 32)
descriptor shape  23  :  (33, 32)
descriptor shape  24  :  (38, 32)
descriptor shape  25  :  (46, 32)
descriptor shape  26  :  (95, 32)
descriptor shape  27  :  (78, 32)
descriptor shape  28  :  (28, 32)
descriptor shape  29  :

In [12]:
#reading previously saved feature descriptor csv file of folder5 and save it into a dataframe
data5= pd.read_csv('folder5.csv',header=None,dtype='uint8')
data5=data5.astype(np.uint8)
data5

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       177  176   79  139   92   98  206  138  176  235  ...   64  221   22   
1        79  154  144  245  243  150   62  101  109   21  ...   52   87  242   
2       181  191   55  161   76   73  193   23  242  170  ...   71  193  147   
3        79  139  145   38  225  141  169  228  108    4  ...   54   67  235   
4        77  202  133   52  247   55  114  100  105  133  ...    4   79  206   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
157780   49   21  110  237   13  162  209  153  178  251  ...  203   56  145   
157781   25    5  108  236   45  187  165  217   16  130  ...  207   42  253   
157782  177   52  110  219   31  114   92   29  177  243  ...  201  172   21   
157783   51   21  110  110   41  226  161  216  178   83  ...  239   40  177   
157784   25   21  126  229   76   41  193  152  242  250  ...  239   24  147   

         25   26   27   28   29   30   31  
0       205  195   40  215  216  194   78  
1        35  152  149    6   38  190  144  
2        94   19  125  201  147  221   14  
3        51   91  133   31   23  191  144  
4        49   26   31   76   40  255  211  
...     ...  ...  ...  ...  ...  ...  ...  
157780  222  101  122  254   93  192  125  
157781  216  229  106  248   93  140  253  
157782  204  165  106  236  252  192  255  
157783  222  101  106  254   93  140  125  
157784  222   97  126  254  215   64  110  

[157785 rows x 32 columns]

In [13]:
#Applying SIFT descriptor on folder6
i=0
for filename in os.listdir(folder6):
    
    path=os.path.join(folder6,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)

    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('folder6.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (6, 32)
descriptor shape  1  :  (97, 32)
descriptor shape  2  :  (165, 32)
descriptor shape  3  :  (9, 32)
descriptor shape  4  :  (264, 32)
descriptor shape  5  :  (243, 32)
descriptor shape  6  :  (162, 32)
descriptor shape  7  :  (171, 32)
descriptor shape  8  :  (192, 32)
descriptor shape  9  :  (256, 32)
descriptor shape  10  :  (182, 32)
descriptor shape  11  :  (120, 32)
descriptor shape  12  :  (107, 32)
descriptor shape  13  :  (92, 32)
descriptor shape  14  :  (144, 32)
descriptor shape  15  :  (137, 32)
descriptor shape  16  :  (193, 32)
descriptor shape  17  :  (166, 32)
descriptor shape  18  :  (217, 32)
descriptor shape  19  :  (287, 32)
descriptor shape  20  :  (278, 32)
descriptor shape  21  :  (330, 32)
descriptor shape  22  :  (249, 32)
descriptor shape  23  :  (152, 32)
descriptor shape  24  :  (267, 32)
descriptor shape  25  :  (135, 32)
descriptor shape  26  :  (308, 32)
descriptor shape  27  :  (266, 32)
descriptor shape  28  :  (326, 32)
d

In [14]:
#reading previously saved feature descriptor csv file of folder6 and save it into a dataframe
data6= pd.read_csv('folder6.csv',header=None,dtype='uint8')
data6=data6.astype(np.uint8)
data6

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       180  252  178   18  196  105  170  244  102   68  ...  223  165  175   
1       230  172  149   51  211   86  254  102   73  133  ...   36  111   15   
2        76  214  129  180  199   55   74  101   89    4  ...   28   47  205   
3        76   71  129  116  227   31  169  236   73    4  ...   46   98  233   
4        78   79  176  116  233   29  169  252   77   20  ...   62   98  249   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
314350   76  214  129  182  231   53  238  100   91    4  ...   28  239  205   
314351   78   79  144  118  225   29  185  228   77    4  ...   62  227  233   
314352   76   79  129  118  227   31  185  228   73    4  ...   62   98  237   
314353   72    6    4   62   39   55  254  109   25  212  ...  136   44  205   
314354   17    1  104  201   52  233    5  155  166  107  ...  243  144   80   

         25   26   27   28   29   30   31  
0       109  115  177   93  193   61    0  
1        35   26   21    0   56  247  146  
2        49  186   27   72   32   62  215  
3        49   56  215   26   45   30  177  
4        48   56  215   26   47   30  176  
...     ...  ...  ...  ...  ...  ...  ...  
314350   49   26   19   72   32   62  215  
314351   49   24  215  153   47   63  176  
314352   49   24  211   27   45   62  177  
314353  145  172  123  110   40  230  247  
314354  236  229  234  116  215  193   41  

[314355 rows x 32 columns]

In [15]:
#append all the class wise feature descriptor data into one data frame
data=data1.append(data2)
data=data.append(data3)
data=data.append(data4)
data=data.append(data5)
data=data.append(data6)
data

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0       79  139  177  196  161  157   41  253  207   20  ...   62   67  243   
1       76  197  192  116  233  183   57  196   93    4  ...  190   98  175   
2       78  206  145   52  231   23  178  101   73    4  ...   60   46  249   
3       78  143  177   55  205   13  201  213   74  132  ...   47  107  233   
4       76   78  133   38  239   39  185  236   74  132  ...   14   42  237   
...     ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
314350  76  214  129  182  231   53  238  100   91    4  ...   28  239  205   
314351  78   79  144  118  225   29  185  228   77    4  ...   62  227  233   
314352  76   79  129  118  227   31  185  228   73    4  ...   62   98  237   
314353  72    6    4   62   39   55  254  109   25  212  ...  136   44  205   
314354  17    1  104  201   52  233    5  155  166  107  ...  243  144   80   

         25   26   27   28   29   30   31  
0        49   28  133   24   23  191  176  
1        33  152  198  136   47   62  133  
2        49   56   23   40   40   63  210  
3       114   26   95   75   17  239    2  
4        49  122   91   57   88  143  243  
...     ...  ...  ...  ...  ...  ...  ...  
314350   49   26   19   72   32   62  215  
314351   49   24  215  153   47   63  176  
314352   49   24  211   27   45   62  177  
314353  145  172  123  110   40  230  247  
314354  236  229  234  116  215  193   41  

[2233095 rows x 32 columns]

In [16]:
#save appended data into a csv file
csv_data=data.to_csv('finalData.csv', mode='a', header=False,index=False)

In [17]:
#read the data from the previously saved csv file
data = pd.read_csv('finalData.csv',header=None)
data

0    1    2    3    4    5    6    7    8    9   ...   22   23   24  \
0        79  139  177  196  161  157   41  253  207   20  ...   62   67  243   
1        76  197  192  116  233  183   57  196   93    4  ...  190   98  175   
2        78  206  145   52  231   23  178  101   73    4  ...   60   46  249   
3        78  143  177   55  205   13  201  213   74  132  ...   47  107  233   
4        76   78  133   38  239   39  185  236   74  132  ...   14   42  237   
...      ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
4466185  76  214  129  182  231   53  238  100   91    4  ...   28  239  205   
4466186  78   79  144  118  225   29  185  228   77    4  ...   62  227  233   
4466187  76   79  129  118  227   31  185  228   73    4  ...   62   98  237   
4466188  72    6    4   62   39   55  254  109   25  212  ...  136   44  205   
4466189  17    1  104  201   52  233    5  155  166  107  ...  243  144   80   

          25   26   27   28   29   30   31  
0         49   28  133   24   23  191  176  
1         33  152  198  136   47   62  133  
2         49   56   23   40   40   63  210  
3        114   26   95   75   17  239    2  
4         49  122   91   57   88  143  243  
...      ...  ...  ...  ...  ...  ...  ...  
4466185   49   26   19   72   32   62  215  
4466186   49   24  215  153   47   63  176  
4466187   49   24  211   27   45   62  177  
4466188  145  172  123  110   40  230  247  
4466189  236  229  234  116  215  193   41  

[4466190 rows x 32 columns]

In [18]:
#Applying Kmeans
kmeans = KMeans(n_clusters=6)
kmeans.fit(data)

KMeans(n_clusters=6)

In [19]:
import pickle

In [20]:
# save the model to disk
filename = 'Kmeans_CL_6_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [21]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5,6])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([755934, 736620, 749070, 889302, 652680, 682584], dtype=int64), array([0, 1, 2, 3, 4, 5, 6])) 



In [22]:
#performing kmeans prediction on the folder1 with the pretrained kmeans model

#initialising i=0; as it is the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)
    
    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6])
    
    #append the dataframe into the array 
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder1.csv', mode='a',header=False,index=False)

445.png
477.png
538.png


In [23]:
#performing kmeans prediction on the folder2 with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array 
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder2.csv', mode='a',header=False,index=False)

In [24]:
#performing kmeans prediction on the folder3 with the pretrained kmeans model

#initialising i=2; as its the 3rd class
i=2
data=[]
k=0
for filename in os.listdir(folder3):
    path=os.path.join(folder3,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array 
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder3.csv', mode='a',header=False,index=False)

In [25]:
#performing kmeans prediction on the folder4 with the pretrained kmeans model

#initialising i=3; as its the 4th class
i=3
data=[]
k=0
for filename in os.listdir(folder4):
    path=os.path.join(folder4,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array 
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder4.csv', mode='a',header=False,index=False)

1009.png
17.png
598.png
795.png
810.png


In [26]:
#performing kmeans prediction on the folder5 with the pretrained kmeans model

#initialising i=4; as its the 5th class
i=4
data=[]
k=0
for filename in os.listdir(folder5):
    path=os.path.join(folder5,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array 
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder5.csv', mode='a',header=False,index=False)

In [27]:
#performing kmeans prediction on the folder6 with the pretrained kmeans model

#initialising i=5; as its the 6th class
i=5
data=[]
k=0
for filename in os.listdir(folder6):
    path=os.path.join(folder6,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(500,500)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Initiate FAST detector
    star = cv2.xfeatures2d.StarDetector_create()
    # Initiate BRIEF extractor
    brief = cv2.xfeatures2d.BriefDescriptorExtractor_create()
    # find the keypoints with STAR
    kp = star.detect(img,None)
    # compute the descriptors with BRIEF
    keypoints, descriptors = brief.compute(gray, kp)
    
    out=pd.DataFrame(descriptors)

    array_double = np.array(out, dtype=np.double)
    try:
        a=kmeans.predict(array_double)
    except:
        print(filename)
    hist=np.histogram(a,bins=[0,1,2,3,4,5,6])
    #append the dataframe into the array 
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('finalFolder6.csv', mode='a',header=False,index=False)

265.png
277.png
605.png


In [28]:
#Displaying the kmeans predicted data of folder1
print("Fridge")
dat1= pd.read_csv('finalFolder1.csv',header=None)
print(dat1)

Fridge
       0   1   2   3   4   5  6
0     23  26   7  13  11   3  0
1     16  22  16  35  23   7  0
2      8  23   5   4   5   1  0
3     34  23  10   8  18   4  0
4     33  32  19  21  20  13  0
...   ..  ..  ..  ..  ..  .. ..
2995  53  60  73  62  57  49  0
2996  57  54  78  71  60  42  0
2997  24  28  11  38  27  31  0
2998  31  35   5  31  26  24  0
2999  12  18   5  14  16   9  0

[3000 rows x 7 columns]


In [29]:
#Displaying the kmeans predicted data of folder2
print("Gas Stove")
dat2= pd.read_csv('finalFolder2.csv',header=None)
print(dat2)

Gas Stove
       0   1   2   3   4   5  6
0     55  62  58  41  36  42  1
1     88  83  76  76  76  57  1
2     11  18   7  31  16   8  1
3     38  23  15  22  25  19  1
4      7  14  14  11   8  13  1
...   ..  ..  ..  ..  ..  .. ..
2995  53  49  40  38  63  38  1
2996  47  58  35  39  65  22  1
2997  47  78  64  51  67  86  1
2998  26  42  57  47  58  57  1
2999  39  50  55  46  68  56  1

[3000 rows x 7 columns]


In [30]:
#Displaying the kmeans predicted data of folder3
print("Induction")
dat3= pd.read_csv('finalFolder3.csv',header=None)
print(dat3)

Induction
       0   1   2   3   4   5  6
0     14  27  28  15  18  28  2
1     36  57  45  60  60  48  2
2     19  77  15  23  23   1  2
3      3  13   5   3   6   0  2
4     24  45   8  18  23   8  2
...   ..  ..  ..  ..  ..  .. ..
2995  49  26  18  73  46  29  2
2996  11   4   1   9   2   1  2
2997   8  15   3  18   4   8  2
2998   8  11   1  25  12   7  2
2999  17  11   7  53   3  18  2

[3000 rows x 7 columns]


In [31]:
#Displaying the kmeans predicted data of folder4
print("Microwave Oven")
dat4= pd.read_csv('finalFolder4.csv',header=None)
print(dat4)

Microwave Oven
       0   1   2   3   4   5  6
0      7  24   6   7   4   0  3
1     12  41  25  29  29  33  3
2      3  18   2   8   1   0  3
3      0   4   3   1   0   0  3
4      0   2   5   5   3   0  3
...   ..  ..  ..  ..  ..  .. ..
3025   4   6   8   1   4   5  3
3026  23  16  23  16  11  24  3
3027   4   3   9   1   4   4  3
3028   5  20   7  23   3   6  3
3029   0   1   1   4   0   0  3

[3030 rows x 7 columns]


In [32]:
#Displaying the kmeans predicted data of folder5
print("Mixer")
dat5= pd.read_csv('finalFolder5.csv',header=None)
print(dat5)

Mixer
       0   1   2  3   4   5  6
0      9   7   1  2   9   6  4
1     11   6   3  5  10   5  4
2      4   0   1  1   1  18  4
3      6   2   4  1   4  24  4
4      6   3  11  1   5  26  4
...   ..  ..  .. ..  ..  .. ..
3010   0   1   3  0   2   0  4
3011   0   3   1  3   2   0  4
3012   0   0   8  1   1   1  4
3013   1   5  16  6   6   6  4
3014   1  11  29  2   8   7  4

[3015 rows x 7 columns]


In [33]:
#Displaying the kmeans predicted data of folder6
print("Water Filter")
dat6= pd.read_csv('finalFolder6.csv',header=None)
print(dat6)

Water Filter
       0   1   2   3   4   5  6
0      1   3   1   0   1   0  5
1     12  26  20  17  11  11  5
2     19  23  23  24  34  42  5
3      1   6   2   0   0   0  5
4     53  37  43  35  53  43  5
...   ..  ..  ..  ..  ..  .. ..
2995  19  27  20  16  11  18  5
2996   8   4   4  19   0   2  5
2997   4   0   6   9   0   3  5
2998   6   0   3  10   1   1  5
2999   3   0   2   8   1   1  5

[3000 rows x 7 columns]


In [34]:
#appending All kmeans predicted data into 1 dataframe
A = dat1.append(dat2)
A = A.append(dat3)
A = A.append(dat4)
A = A.append(dat5)
A = A.append(dat6)
A

0   1   2   3   4   5  6
0     23  26   7  13  11   3  0
1     16  22  16  35  23   7  0
2      8  23   5   4   5   1  0
3     34  23  10   8  18   4  0
4     33  32  19  21  20  13  0
...   ..  ..  ..  ..  ..  .. ..
2995  19  27  20  16  11  18  5
2996   8   4   4  19   0   2  5
2997   4   0   6   9   0   3  5
2998   6   0   3  10   1   1  5
2999   3   0   2   8   1   1  5

[18045 rows x 7 columns]

In [35]:
#save the predicted data into csv file
csv_data=A.to_csv('FinalF.csv', mode='a',header=False,index=False)

In [36]:
#read the data from the previously saved csv file
A = pd.read_csv("FinalF.csv",header=None)
A

0   1   2   3   4   5  6
0      23  26   7  13  11   3  0
1      16  22  16  35  23   7  0
2       8  23   5   4   5   1  0
3      34  23  10   8  18   4  0
4      33  32  19  21  20  13  0
...    ..  ..  ..  ..  ..  .. ..
36085  19  27  20  16  11  18  5
36086   8   4   4  19   0   2  5
36087   4   0   6   9   0   3  5
36088   6   0   3  10   1   1  5
36089   3   0   2   8   1   1  5

[36090 rows x 7 columns]

In [37]:
#assigning x the columns from 0 to 2 for training
x = A.iloc[:,0:6].values
x
#performing Normalization 
from sklearn import preprocessing
a=preprocessing.normalize(x, axis=0)
scaled_df= pd.DataFrame(a)
x=scaled_df

In [38]:
#assigning y with the column 3 as target variable
y = A.iloc[:,6].values
y

array([0, 0, 0, ..., 5, 5, 5], dtype=int64)

In [39]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [40]:
Dhoni

array([[-0.0019658 ,  0.04317882, -0.20302896, -0.11787487, -0.10322954,
        -0.07252148],
       [-0.03684563, -0.02689993, -0.07132878,  0.12589111, -0.00919481,
        -0.06308283],
       [-0.0767083 , -0.00938024, -0.23229567, -0.21759732, -0.1502469 ,
        -0.0772408 ],
       ...,
       [-0.09663963, -0.412333  , -0.21766231, -0.16219596, -0.18942804,
        -0.07252148],
       [-0.08667397, -0.412333  , -0.26156237, -0.15111569, -0.18159181,
        -0.0772408 ],
       [-0.10162247, -0.412333  , -0.27619572, -0.17327623, -0.18159181,
        -0.0772408 ]])

In [41]:
from sklearn.decomposition import PCA

In [42]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [43]:
Bhumi = pca.transform(Dhoni)
Bhumi

array([[-0.19772606,  0.07843797, -0.0005478 , -0.16177673,  0.02498559,
        -0.02923732],
       [-0.02651446, -0.02477762, -0.01548072, -0.03612137, -0.148469  ,
         0.04666009],
       [-0.32276721,  0.03882513, -0.01174026, -0.14321269,  0.07965266,
        -0.05607121],
       ...,
       [-0.47813692, -0.10595132,  0.2091435 ,  0.08960879, -0.05045629,
        -0.00522557],
       [-0.48787907, -0.10617275,  0.22624427,  0.05231772, -0.06650854,
         0.00882032],
       [-0.50905759, -0.11495142,  0.22113589,  0.04182164, -0.05017456,
         0.00866117]])

In [44]:
Bhumi = pd.DataFrame(Bhumi)
Bhumi

0         1         2         3         4         5
0     -0.197726  0.078438 -0.000548 -0.161777  0.024986 -0.029237
1     -0.026514 -0.024778 -0.015481 -0.036121 -0.148469  0.046660
2     -0.322767  0.038825 -0.011740 -0.143213  0.079653 -0.056071
3     -0.182583  0.091604  0.059625 -0.106871  0.091932  0.018279
4      0.018046  0.120078 -0.068881 -0.092865  0.026926 -0.022688
...         ...       ...       ...       ...       ...       ...
36085 -0.084219  0.070279 -0.064456 -0.020035  0.041163 -0.072408
36086 -0.407353 -0.086890  0.184882  0.023859 -0.140668 -0.010137
36087 -0.478137 -0.105951  0.209144  0.089609 -0.050456 -0.005226
36088 -0.487879 -0.106173  0.226244  0.052318 -0.066509  0.008820
36089 -0.509058 -0.114951  0.221136  0.041822 -0.050175  0.008661

[36090 rows x 6 columns]

In [45]:
Bhumi.shape

(36090, 6)

In [46]:
print(pca.explained_variance_ratio_) 

[0.80993671 0.14668389 0.03481133 0.00473303 0.00246859 0.00136645]


In [47]:
pca = PCA(n_components=6)
pca.fit(Dhoni)

PCA(n_components=6)

In [48]:
# save the model to disk
import pickle

filename = 'PCA_6_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [49]:
Bhumi = pca.transform(Dhoni)
Bhumi

array([[-0.19772606,  0.07843797, -0.0005478 , -0.16177673,  0.02498559,
        -0.02923732],
       [-0.02651446, -0.02477762, -0.01548072, -0.03612137, -0.148469  ,
         0.04666009],
       [-0.32276721,  0.03882513, -0.01174026, -0.14321269,  0.07965266,
        -0.05607121],
       ...,
       [-0.47813692, -0.10595132,  0.2091435 ,  0.08960879, -0.05045629,
        -0.00522557],
       [-0.48787907, -0.10617275,  0.22624427,  0.05231772, -0.06650854,
         0.00882032],
       [-0.50905759, -0.11495142,  0.22113589,  0.04182164, -0.05017456,
         0.00866117]])

In [50]:
Bhumi.shape

(36090, 6)

In [51]:
print(pca.explained_variance_ratio_) 

[0.80993671 0.14668389 0.03481133 0.00473303 0.00246859 0.00136645]


In [52]:
Bhumi = pd.DataFrame(Bhumi)
Bhumi

0         1         2         3         4         5
0     -0.197726  0.078438 -0.000548 -0.161777  0.024986 -0.029237
1     -0.026514 -0.024778 -0.015481 -0.036121 -0.148469  0.046660
2     -0.322767  0.038825 -0.011740 -0.143213  0.079653 -0.056071
3     -0.182583  0.091604  0.059625 -0.106871  0.091932  0.018279
4      0.018046  0.120078 -0.068881 -0.092865  0.026926 -0.022688
...         ...       ...       ...       ...       ...       ...
36085 -0.084219  0.070279 -0.064456 -0.020035  0.041163 -0.072408
36086 -0.407353 -0.086890  0.184882  0.023859 -0.140668 -0.010137
36087 -0.478137 -0.105951  0.209144  0.089609 -0.050456 -0.005226
36088 -0.487879 -0.106173  0.226244  0.052318 -0.066509  0.008820
36089 -0.509058 -0.114951  0.221136  0.041822 -0.050175  0.008661

[36090 rows x 6 columns]

In [53]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)
B

0         1         2         3         4         5  0
0     -0.197726  0.078438 -0.000548 -0.161777  0.024986 -0.029237  0
1     -0.026514 -0.024778 -0.015481 -0.036121 -0.148469  0.046660  0
2     -0.322767  0.038825 -0.011740 -0.143213  0.079653 -0.056071  0
3     -0.182583  0.091604  0.059625 -0.106871  0.091932  0.018279  0
4      0.018046  0.120078 -0.068881 -0.092865  0.026926 -0.022688  0
...         ...       ...       ...       ...       ...       ... ..
36085 -0.084219  0.070279 -0.064456 -0.020035  0.041163 -0.072408  5
36086 -0.407353 -0.086890  0.184882  0.023859 -0.140668 -0.010137  5
36087 -0.478137 -0.105951  0.209144  0.089609 -0.050456 -0.005226  5
36088 -0.487879 -0.106173  0.226244  0.052318 -0.066509  0.008820  5
36089 -0.509058 -0.114951  0.221136  0.041822 -0.050175  0.008661  5

[36090 rows x 7 columns]

In [54]:
csv_data=B.to_csv('FinalPCAFV.csv', mode='a',header=False,index=False)

In [55]:
data= pd.read_csv('FinalPCAFV.csv',header=None)

data

0         1         2         3         4         5  6
0     -0.211654  0.066402  0.027617 -0.135434  0.008798 -0.032524  0
1     -0.039241 -0.036587  0.017576  0.016136  0.173493  0.005121  0
2     -0.336481  0.026808  0.016316 -0.125906 -0.053635 -0.041722  0
3     -0.196133  0.079949  0.088401 -0.098570 -0.050496  0.036193  0
4      0.003768  0.108045 -0.037402 -0.064999 -0.002314 -0.019893  0
...         ...       ...       ...       ...       ...       ... ..
60145 -0.084219  0.070279 -0.064456 -0.020035  0.041163 -0.072408  5
60146 -0.407353 -0.086890  0.184882  0.023859 -0.140668 -0.010137  5
60147 -0.478137 -0.105951  0.209144  0.089609 -0.050456 -0.005226  5
60148 -0.487879 -0.106173  0.226244  0.052318 -0.066509  0.008820  5
60149 -0.509058 -0.114951  0.221136  0.041822 -0.050175  0.008661  5

[60150 rows x 7 columns]

In [56]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:6].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,6]
print("Y values")
print(y)

X values
[[-0.21165369  0.06640186  0.02761679 -0.13543427  0.00879803 -0.03252418]
 [-0.0392407  -0.03658748  0.0175757   0.01613554  0.17349255  0.00512061]
 [-0.33648082  0.02680819  0.01631555 -0.12590624 -0.05363452 -0.04172217]
 ...
 [-0.47813692 -0.10595132  0.2091435   0.08960879 -0.05045629 -0.00522557]
 [-0.48787907 -0.10617275  0.22624427  0.05231772 -0.06650854  0.00882032]
 [-0.50905759 -0.11495142  0.22113589  0.04182164 -0.05017456  0.00866117]]
Y values
0        0
1        0
2        0
3        0
4        0
        ..
60145    5
60146    5
60147    5
60148    5
60149    5
Name: 6, Length: 60150, dtype: int64


In [57]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [58]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

Decision Tree Results
Decision Tree Accuracy:  62.776392352452206 %


In [59]:
print(metrics.confusion_matrix(y_test, y_pred1))
print(metrics.classification_report(y_test, y_pred1))

[[1130  195  107  266   58  263]
 [ 192 1566   45   49    3  148]
 [ 155  139 1239  213   68  179]
 [ 240  156  155 1032   84  338]
 [  71    2   63  157 1632   88]
 [ 287  163  182  341   71  953]]
              precision    recall  f1-score   support

           0       0.54      0.56      0.55      2019
           1       0.71      0.78      0.74      2003
           2       0.69      0.62      0.65      1993
           3       0.50      0.51      0.51      2005
           4       0.85      0.81      0.83      2013
           5       0.48      0.48      0.48      1997

    accuracy                           0.63     12030
   macro avg       0.63      0.63      0.63     12030
weighted avg       0.63      0.63      0.63     12030



In [61]:
#KNN

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
 
knn = KNeighborsClassifier(n_neighbors=7)
     
knn.fit(x_train, y_train)
knn.fit(x_test, y_test) 
y_pred = knn.predict(x_test)

# Calculate the accuracy of the model
print("KNN Results")
print("KNN Accuracy: ",knn.score(x_test, y_test)*100,"%")

KNN Results
KNN Accuracy:  67.0739817123857 %


In [62]:
# Performance Metrics
from sklearn import metrics

print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.classification_report(y_test, y_pred))

[[1386  151   75  210   37  160]
 [ 172 1670   33   47    1   80]
 [ 211  193 1246  127   81  135]
 [ 324  162  139 1095  107  178]
 [  93   11   54   92 1690   73]
 [ 307  209  133  275   91  982]]
              precision    recall  f1-score   support

           0       0.56      0.69      0.61      2019
           1       0.70      0.83      0.76      2003
           2       0.74      0.63      0.68      1993
           3       0.59      0.55      0.57      2005
           4       0.84      0.84      0.84      2013
           5       0.61      0.49      0.54      1997

    accuracy                           0.67     12030
   macro avg       0.67      0.67      0.67     12030
weighted avg       0.67      0.67      0.67     12030



In [64]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='log2',
                                max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, 
                                n_jobs=None, random_state=2, verbose=0, warm_start=False, class_weight=None, 
                                ccp_alpha=0.0, max_samples=None)
filename = 'model4.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
#Results
print("RandomF Results")
print("RandomF Accuracy: ",accuracy_score(y_test, y_pred4)*100,"%")

RandomF Results
RandomF Accuracy:  89.12718204488777 %


In [65]:
# Performance Metrics
from sklearn import metrics

print(metrics.confusion_matrix(y_test, y_pred4))
print(metrics.classification_report(y_test, y_pred4))

[[1781   42   38   68   27   63]
 [  29 1907   19    8    0   40]
 [  32   47 1762   54   25   73]
 [  70   49   55 1727   37   67]
 [  26    0   16   29 1914   28]
 [  90   79   65   79   53 1631]]
              precision    recall  f1-score   support

           0       0.88      0.88      0.88      2019
           1       0.90      0.95      0.92      2003
           2       0.90      0.88      0.89      1993
           3       0.88      0.86      0.87      2005
           4       0.93      0.95      0.94      2013
           5       0.86      0.82      0.84      1997

    accuracy                           0.89     12030
   macro avg       0.89      0.89      0.89     12030
weighted avg       0.89      0.89      0.89     12030

